// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/tpu/dynamic_padding.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A mapping between the dynamic shape dimension of an input and the arg that
// represents the real shape.
type PaddingMap struct {
	// Input arg index with dynamic shapes.
	ArgIndex int32 `protobuf:"varint,1,opt,name=arg_index,json=argIndex,proto3" json:"arg_index,omitempty"`
	// The dynamic shape dimension index.
	ShapeIndex int32 `protobuf:"varint,2,opt,name=shape_index,json=shapeIndex,proto3" json:"shape_index,omitempty"`
	// The arg index that dynamic dimension maps to, which represents the value
	// of the real shape.
	PaddingArgIndex      int32    `protobuf:"varint,3,opt,name=padding_arg_index,json=paddingArgIndex,proto3" json:"padding_arg_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaddingMap) Reset()         { *m = PaddingMap{} }
func (m *PaddingMap) String() string { return proto.CompactTextString(m) }
func (*PaddingMap) ProtoMessage()    {}
func (*PaddingMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_81091206b1d6f06f, []int{0}
}

func (m *PaddingMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaddingMap.Unmarshal(m, b)
}
func (m *PaddingMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaddingMap.Marshal(b, m, deterministic)
}
func (m *PaddingMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaddingMap.Merge(m, src)
}
func (m *PaddingMap) XXX_Size() int {
	return xxx_messageInfo_PaddingMap.Size(m)
}
func (m *PaddingMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PaddingMap.DiscardUnknown(m)
}

var xxx_messageInfo_PaddingMap proto.InternalMessageInfo

func (m *PaddingMap) GetArgIndex() int32 {
	if m != nil {
		return m.ArgIndex
	}
	return 0
}

func (m *PaddingMap) GetShapeIndex() int32 {
	if m != nil {
		return m.ShapeIndex
	}
	return 0
}

func (m *PaddingMap) GetPaddingArgIndex() int32 {
	if m != nil {
		return m.PaddingArgIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*PaddingMap)(nil), "tensorflow.tpu.PaddingMap")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/tpu/dynamic_padding.proto", fileDescriptor_81091206b1d6f06f)
}

var fileDescriptor_81091206b1d6f06f = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2a, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x29, 0x28, 0xd5, 0x4f, 0xa9, 0xcc, 0x4b, 0xcc, 0xcd, 0x4c,
	0x8e, 0x2f, 0x48, 0x4c, 0x49, 0xc9, 0xcc, 0x4b, 0xd7, 0x03, 0x4b, 0x0a, 0xf1, 0x21, 0xf4, 0xe8,
	0x95, 0x14, 0x94, 0x2a, 0x95, 0x71, 0x71, 0x05, 0x40, 0x14, 0xf8, 0x26, 0x16, 0x08, 0x49, 0x73,
	0x71, 0x26, 0x16, 0xa5, 0xc7, 0x67, 0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x71, 0x24, 0x16, 0xa5, 0x7b, 0x82, 0xf8, 0x42, 0xf2, 0x5c, 0xdc, 0xc5, 0x19, 0x89, 0x05,
	0xa9, 0x50, 0x69, 0x26, 0xb0, 0x34, 0x17, 0x58, 0x08, 0xa2, 0x40, 0x8b, 0x4b, 0x10, 0x6a, 0x59,
	0x3c, 0xc2, 0x14, 0x66, 0xb0, 0x32, 0x7e, 0xa8, 0x84, 0x23, 0xd4, 0x30, 0x27, 0xc7, 0x28, 0x9b,
	0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x24, 0x8f, 0x60, 0x67, 0xa6,
	0xe7, 0xa3, 0xfa, 0xf0, 0x07, 0x23, 0x63, 0x12, 0x1b, 0x98, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xce, 0x4c, 0xc4, 0xc1, 0x07, 0x01, 0x00, 0x00,
}
