// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/graph_debug_info.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GraphDebugInfo struct {
	// This stores all the source code file names and can be indexed by the
	// `file_index`.
	Files []string `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// This maps a node name to a stack trace in the source code.
	Traces               map[string]*GraphDebugInfo_StackTrace `protobuf:"bytes,2,rep,name=traces,proto3" json:"traces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *GraphDebugInfo) Reset()         { *m = GraphDebugInfo{} }
func (m *GraphDebugInfo) String() string { return proto.CompactTextString(m) }
func (*GraphDebugInfo) ProtoMessage()    {}
func (*GraphDebugInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d49d5c184d173e1, []int{0}
}

func (m *GraphDebugInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphDebugInfo.Unmarshal(m, b)
}
func (m *GraphDebugInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphDebugInfo.Marshal(b, m, deterministic)
}
func (m *GraphDebugInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDebugInfo.Merge(m, src)
}
func (m *GraphDebugInfo) XXX_Size() int {
	return xxx_messageInfo_GraphDebugInfo.Size(m)
}
func (m *GraphDebugInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDebugInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDebugInfo proto.InternalMessageInfo

func (m *GraphDebugInfo) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *GraphDebugInfo) GetTraces() map[string]*GraphDebugInfo_StackTrace {
	if m != nil {
		return m.Traces
	}
	return nil
}

// This represents a file/line location in the source code.
type GraphDebugInfo_FileLineCol struct {
	// File name index, which can be used to retrieve the file name string from
	// `files`. The value should be between 0 and (len(files)-1)
	FileIndex int32 `protobuf:"varint,1,opt,name=file_index,json=fileIndex,proto3" json:"file_index,omitempty"`
	// Line number in the file.
	Line int32 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	// Col number in the file line.
	Col int32 `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	// Name of function contains the file line.
	Func string `protobuf:"bytes,4,opt,name=func,proto3" json:"func,omitempty"`
	// Source code contained in this file line.
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphDebugInfo_FileLineCol) Reset()         { *m = GraphDebugInfo_FileLineCol{} }
func (m *GraphDebugInfo_FileLineCol) String() string { return proto.CompactTextString(m) }
func (*GraphDebugInfo_FileLineCol) ProtoMessage()    {}
func (*GraphDebugInfo_FileLineCol) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d49d5c184d173e1, []int{0, 0}
}

func (m *GraphDebugInfo_FileLineCol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphDebugInfo_FileLineCol.Unmarshal(m, b)
}
func (m *GraphDebugInfo_FileLineCol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphDebugInfo_FileLineCol.Marshal(b, m, deterministic)
}
func (m *GraphDebugInfo_FileLineCol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDebugInfo_FileLineCol.Merge(m, src)
}
func (m *GraphDebugInfo_FileLineCol) XXX_Size() int {
	return xxx_messageInfo_GraphDebugInfo_FileLineCol.Size(m)
}
func (m *GraphDebugInfo_FileLineCol) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDebugInfo_FileLineCol.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDebugInfo_FileLineCol proto.InternalMessageInfo

func (m *GraphDebugInfo_FileLineCol) GetFileIndex() int32 {
	if m != nil {
		return m.FileIndex
	}
	return 0
}

func (m *GraphDebugInfo_FileLineCol) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *GraphDebugInfo_FileLineCol) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *GraphDebugInfo_FileLineCol) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *GraphDebugInfo_FileLineCol) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

// This represents a stack trace which is a ordered list of `FileLineCol`.
type GraphDebugInfo_StackTrace struct {
	// Each line in the stack trace.
	FileLineCols         []*GraphDebugInfo_FileLineCol `protobuf:"bytes,1,rep,name=file_line_cols,json=fileLineCols,proto3" json:"file_line_cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GraphDebugInfo_StackTrace) Reset()         { *m = GraphDebugInfo_StackTrace{} }
func (m *GraphDebugInfo_StackTrace) String() string { return proto.CompactTextString(m) }
func (*GraphDebugInfo_StackTrace) ProtoMessage()    {}
func (*GraphDebugInfo_StackTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d49d5c184d173e1, []int{0, 1}
}

func (m *GraphDebugInfo_StackTrace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphDebugInfo_StackTrace.Unmarshal(m, b)
}
func (m *GraphDebugInfo_StackTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphDebugInfo_StackTrace.Marshal(b, m, deterministic)
}
func (m *GraphDebugInfo_StackTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphDebugInfo_StackTrace.Merge(m, src)
}
func (m *GraphDebugInfo_StackTrace) XXX_Size() int {
	return xxx_messageInfo_GraphDebugInfo_StackTrace.Size(m)
}
func (m *GraphDebugInfo_StackTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphDebugInfo_StackTrace.DiscardUnknown(m)
}

var xxx_messageInfo_GraphDebugInfo_StackTrace proto.InternalMessageInfo

func (m *GraphDebugInfo_StackTrace) GetFileLineCols() []*GraphDebugInfo_FileLineCol {
	if m != nil {
		return m.FileLineCols
	}
	return nil
}

func init() {
	proto.RegisterType((*GraphDebugInfo)(nil), "tensorflow.GraphDebugInfo")
	proto.RegisterMapType((map[string]*GraphDebugInfo_StackTrace)(nil), "tensorflow.GraphDebugInfo.TracesEntry")
	proto.RegisterType((*GraphDebugInfo_FileLineCol)(nil), "tensorflow.GraphDebugInfo.FileLineCol")
	proto.RegisterType((*GraphDebugInfo_StackTrace)(nil), "tensorflow.GraphDebugInfo.StackTrace")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/graph_debug_info.proto", fileDescriptor_2d49d5c184d173e1)
}

var fileDescriptor_2d49d5c184d173e1 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcf, 0x6b, 0xdb, 0x30,
	0x18, 0x45, 0x71, 0x1c, 0xf0, 0xe7, 0x11, 0x86, 0xc8, 0x41, 0x04, 0x06, 0x66, 0xb0, 0xe1, 0x93,
	0x0d, 0xd9, 0x65, 0x6c, 0x63, 0x87, 0xf4, 0x17, 0x81, 0x1c, 0x82, 0xdb, 0x53, 0x2e, 0xae, 0xad,
	0x48, 0x8e, 0x89, 0x22, 0x05, 0xd9, 0x6e, 0x9a, 0xfe, 0x35, 0xfd, 0x33, 0x7b, 0x2c, 0x92, 0x0b,
	0x76, 0xa0, 0xe4, 0xf6, 0xbe, 0xa7, 0xef, 0x3d, 0xbd, 0x87, 0x04, 0x71, 0xcd, 0x64, 0xa5, 0x34,
	0x17, 0xea, 0x18, 0x53, 0xa5, 0x59, 0x7c, 0xd0, 0xaa, 0x56, 0x79, 0xc3, 0xe3, 0x42, 0x67, 0x87,
	0x6d, 0xba, 0x61, 0x79, 0x53, 0xa4, 0xa5, 0xe4, 0x2a, 0xb2, 0x27, 0x18, 0x3a, 0xc1, 0xf7, 0x57,
	0x07, 0xc6, 0x77, 0x66, 0xed, 0xda, 0x6c, 0x2d, 0x24, 0x57, 0x78, 0x02, 0x2e, 0x2f, 0x05, 0xab,
	0x08, 0x0a, 0x9c, 0xd0, 0x4b, 0xda, 0x01, 0xff, 0x87, 0x51, 0xad, 0x33, 0xca, 0x2a, 0x32, 0x08,
	0x9c, 0xd0, 0x9f, 0xfd, 0x8c, 0x3a, 0x97, 0xe8, 0xdc, 0x21, 0x7a, 0xb0, 0x8b, 0x37, 0xb2, 0xd6,
	0xa7, 0xe4, 0x43, 0x35, 0x7d, 0x01, 0xff, 0xb6, 0x14, 0x6c, 0x59, 0x4a, 0x76, 0xa5, 0x04, 0xfe,
	0x06, 0x60, 0x7c, 0xd3, 0x52, 0x6e, 0xd8, 0x33, 0x41, 0x01, 0x0a, 0xdd, 0xc4, 0x33, 0xcc, 0xc2,
	0x10, 0x18, 0xc3, 0x50, 0x94, 0x92, 0x91, 0x81, 0x3d, 0xb0, 0x18, 0x7f, 0x05, 0x87, 0x2a, 0x41,
	0x1c, 0x4b, 0x19, 0x68, 0xb6, 0x78, 0x23, 0x29, 0x19, 0x06, 0x28, 0xf4, 0x12, 0x8b, 0x0d, 0x47,
	0xd5, 0x86, 0x11, 0xb7, 0xe5, 0x0c, 0x9e, 0xae, 0x01, 0xee, 0xeb, 0x8c, 0xee, 0x6c, 0x2e, 0xbc,
	0x84, 0xb1, 0xbd, 0xda, 0x98, 0xa6, 0x54, 0x89, 0xb6, 0xe8, 0xe5, 0x46, 0xbd, 0xe8, 0xc9, 0x17,
	0xde, 0x0d, 0xd5, 0xf4, 0x11, 0xfc, 0x5e, 0x5d, 0x13, 0x72, 0xc7, 0x4e, 0xb6, 0x90, 0x97, 0x18,
	0x88, 0xff, 0x82, 0xfb, 0x94, 0x89, 0xa6, 0xed, 0xe2, 0xcf, 0x7e, 0x5c, 0xb8, 0xa5, 0x0b, 0x99,
	0xb4, 0x9a, 0x3f, 0x83, 0xdf, 0x68, 0x5e, 0x01, 0x51, 0xba, 0xe8, 0xcb, 0xb8, 0xce, 0xf6, 0xec,
	0xa8, 0xf4, 0x6e, 0x3e, 0x39, 0x77, 0x58, 0x99, 0xf7, 0xad, 0x56, 0x68, 0xfd, 0xaf, 0x28, 0xeb,
	0x6d, 0x93, 0x47, 0x54, 0xed, 0xfb, 0xdf, 0xe3, 0x73, 0x58, 0xa8, 0xf3, 0x7f, 0xf3, 0x86, 0x50,
	0x3e, 0xb2, 0xc3, 0xaf, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0x36, 0x2a, 0x1d, 0x5d, 0x02,
	0x00, 0x00,
}
