// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/replay_log.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Records the creation of a new replay session.  We record the device listing
// here to capture the state of the cluster.
type NewReplaySession struct {
	Devices              *ListDevicesResponse `protobuf:"bytes,1,opt,name=devices,proto3" json:"devices,omitempty"`
	SessionHandle        string               `protobuf:"bytes,2,opt,name=session_handle,json=sessionHandle,proto3" json:"session_handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NewReplaySession) Reset()         { *m = NewReplaySession{} }
func (m *NewReplaySession) String() string { return proto.CompactTextString(m) }
func (*NewReplaySession) ProtoMessage()    {}
func (*NewReplaySession) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee59cdea95caad8, []int{0}
}

func (m *NewReplaySession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewReplaySession.Unmarshal(m, b)
}
func (m *NewReplaySession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewReplaySession.Marshal(b, m, deterministic)
}
func (m *NewReplaySession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewReplaySession.Merge(m, src)
}
func (m *NewReplaySession) XXX_Size() int {
	return xxx_messageInfo_NewReplaySession.Size(m)
}
func (m *NewReplaySession) XXX_DiscardUnknown() {
	xxx_messageInfo_NewReplaySession.DiscardUnknown(m)
}

var xxx_messageInfo_NewReplaySession proto.InternalMessageInfo

func (m *NewReplaySession) GetDevices() *ListDevicesResponse {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *NewReplaySession) GetSessionHandle() string {
	if m != nil {
		return m.SessionHandle
	}
	return ""
}

type ReplayOp struct {
	StartTimeUs float64 `protobuf:"fixed64,31,opt,name=start_time_us,json=startTimeUs,proto3" json:"start_time_us,omitempty"`
	EndTimeUs   float64 `protobuf:"fixed64,32,opt,name=end_time_us,json=endTimeUs,proto3" json:"end_time_us,omitempty"`
	// Types that are valid to be assigned to Op:
	//	*ReplayOp_CreateSession
	//	*ReplayOp_ExtendSession
	//	*ReplayOp_PartialRunSetup
	//	*ReplayOp_RunStep
	//	*ReplayOp_CloseSession
	//	*ReplayOp_ListDevices
	//	*ReplayOp_ResetRequest
	//	*ReplayOp_MakeCallable
	//	*ReplayOp_RunCallable
	//	*ReplayOp_ReleaseCallable
	//	*ReplayOp_NewReplaySession
	Op isReplayOp_Op `protobuf_oneof:"op"`
	// Types that are valid to be assigned to Response:
	//	*ReplayOp_CreateSessionResponse
	//	*ReplayOp_ExtendSessionResponse
	//	*ReplayOp_PartialRunSetupResponse
	//	*ReplayOp_RunStepResponse
	//	*ReplayOp_CloseSessionResponse
	//	*ReplayOp_ListDevicesResponse
	//	*ReplayOp_ResetRequestResponse
	//	*ReplayOp_MakeCallableResponse
	//	*ReplayOp_RunCallableResponse
	//	*ReplayOp_ReleaseCallableResponse
	Response             isReplayOp_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReplayOp) Reset()         { *m = ReplayOp{} }
func (m *ReplayOp) String() string { return proto.CompactTextString(m) }
func (*ReplayOp) ProtoMessage()    {}
func (*ReplayOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee59cdea95caad8, []int{1}
}

func (m *ReplayOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplayOp.Unmarshal(m, b)
}
func (m *ReplayOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplayOp.Marshal(b, m, deterministic)
}
func (m *ReplayOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplayOp.Merge(m, src)
}
func (m *ReplayOp) XXX_Size() int {
	return xxx_messageInfo_ReplayOp.Size(m)
}
func (m *ReplayOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplayOp.DiscardUnknown(m)
}

var xxx_messageInfo_ReplayOp proto.InternalMessageInfo

func (m *ReplayOp) GetStartTimeUs() float64 {
	if m != nil {
		return m.StartTimeUs
	}
	return 0
}

func (m *ReplayOp) GetEndTimeUs() float64 {
	if m != nil {
		return m.EndTimeUs
	}
	return 0
}

type isReplayOp_Op interface {
	isReplayOp_Op()
}

type ReplayOp_CreateSession struct {
	CreateSession *CreateSessionRequest `protobuf:"bytes,1,opt,name=create_session,json=createSession,proto3,oneof"`
}

type ReplayOp_ExtendSession struct {
	ExtendSession *ExtendSessionRequest `protobuf:"bytes,2,opt,name=extend_session,json=extendSession,proto3,oneof"`
}

type ReplayOp_PartialRunSetup struct {
	PartialRunSetup *PartialRunSetupRequest `protobuf:"bytes,3,opt,name=partial_run_setup,json=partialRunSetup,proto3,oneof"`
}

type ReplayOp_RunStep struct {
	RunStep *RunStepRequest `protobuf:"bytes,4,opt,name=run_step,json=runStep,proto3,oneof"`
}

type ReplayOp_CloseSession struct {
	CloseSession *CloseSessionRequest `protobuf:"bytes,5,opt,name=close_session,json=closeSession,proto3,oneof"`
}

type ReplayOp_ListDevices struct {
	ListDevices *ListDevicesRequest `protobuf:"bytes,6,opt,name=list_devices,json=listDevices,proto3,oneof"`
}

type ReplayOp_ResetRequest struct {
	ResetRequest *ResetRequest `protobuf:"bytes,7,opt,name=reset_request,json=resetRequest,proto3,oneof"`
}

type ReplayOp_MakeCallable struct {
	MakeCallable *MakeCallableRequest `protobuf:"bytes,8,opt,name=make_callable,json=makeCallable,proto3,oneof"`
}

type ReplayOp_RunCallable struct {
	RunCallable *RunCallableRequest `protobuf:"bytes,9,opt,name=run_callable,json=runCallable,proto3,oneof"`
}

type ReplayOp_ReleaseCallable struct {
	ReleaseCallable *ReleaseCallableRequest `protobuf:"bytes,10,opt,name=release_callable,json=releaseCallable,proto3,oneof"`
}

type ReplayOp_NewReplaySession struct {
	NewReplaySession *NewReplaySession `protobuf:"bytes,11,opt,name=new_replay_session,json=newReplaySession,proto3,oneof"`
}

func (*ReplayOp_CreateSession) isReplayOp_Op() {}

func (*ReplayOp_ExtendSession) isReplayOp_Op() {}

func (*ReplayOp_PartialRunSetup) isReplayOp_Op() {}

func (*ReplayOp_RunStep) isReplayOp_Op() {}

func (*ReplayOp_CloseSession) isReplayOp_Op() {}

func (*ReplayOp_ListDevices) isReplayOp_Op() {}

func (*ReplayOp_ResetRequest) isReplayOp_Op() {}

func (*ReplayOp_MakeCallable) isReplayOp_Op() {}

func (*ReplayOp_RunCallable) isReplayOp_Op() {}

func (*ReplayOp_ReleaseCallable) isReplayOp_Op() {}

func (*ReplayOp_NewReplaySession) isReplayOp_Op() {}

func (m *ReplayOp) GetOp() isReplayOp_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *ReplayOp) GetCreateSession() *CreateSessionRequest {
	if x, ok := m.GetOp().(*ReplayOp_CreateSession); ok {
		return x.CreateSession
	}
	return nil
}

func (m *ReplayOp) GetExtendSession() *ExtendSessionRequest {
	if x, ok := m.GetOp().(*ReplayOp_ExtendSession); ok {
		return x.ExtendSession
	}
	return nil
}

func (m *ReplayOp) GetPartialRunSetup() *PartialRunSetupRequest {
	if x, ok := m.GetOp().(*ReplayOp_PartialRunSetup); ok {
		return x.PartialRunSetup
	}
	return nil
}

func (m *ReplayOp) GetRunStep() *RunStepRequest {
	if x, ok := m.GetOp().(*ReplayOp_RunStep); ok {
		return x.RunStep
	}
	return nil
}

func (m *ReplayOp) GetCloseSession() *CloseSessionRequest {
	if x, ok := m.GetOp().(*ReplayOp_CloseSession); ok {
		return x.CloseSession
	}
	return nil
}

func (m *ReplayOp) GetListDevices() *ListDevicesRequest {
	if x, ok := m.GetOp().(*ReplayOp_ListDevices); ok {
		return x.ListDevices
	}
	return nil
}

func (m *ReplayOp) GetResetRequest() *ResetRequest {
	if x, ok := m.GetOp().(*ReplayOp_ResetRequest); ok {
		return x.ResetRequest
	}
	return nil
}

func (m *ReplayOp) GetMakeCallable() *MakeCallableRequest {
	if x, ok := m.GetOp().(*ReplayOp_MakeCallable); ok {
		return x.MakeCallable
	}
	return nil
}

func (m *ReplayOp) GetRunCallable() *RunCallableRequest {
	if x, ok := m.GetOp().(*ReplayOp_RunCallable); ok {
		return x.RunCallable
	}
	return nil
}

func (m *ReplayOp) GetReleaseCallable() *ReleaseCallableRequest {
	if x, ok := m.GetOp().(*ReplayOp_ReleaseCallable); ok {
		return x.ReleaseCallable
	}
	return nil
}

func (m *ReplayOp) GetNewReplaySession() *NewReplaySession {
	if x, ok := m.GetOp().(*ReplayOp_NewReplaySession); ok {
		return x.NewReplaySession
	}
	return nil
}

type isReplayOp_Response interface {
	isReplayOp_Response()
}

type ReplayOp_CreateSessionResponse struct {
	CreateSessionResponse *CreateSessionResponse `protobuf:"bytes,21,opt,name=create_session_response,json=createSessionResponse,proto3,oneof"`
}

type ReplayOp_ExtendSessionResponse struct {
	ExtendSessionResponse *ExtendSessionResponse `protobuf:"bytes,22,opt,name=extend_session_response,json=extendSessionResponse,proto3,oneof"`
}

type ReplayOp_PartialRunSetupResponse struct {
	PartialRunSetupResponse *PartialRunSetupResponse `protobuf:"bytes,23,opt,name=partial_run_setup_response,json=partialRunSetupResponse,proto3,oneof"`
}

type ReplayOp_RunStepResponse struct {
	RunStepResponse *RunStepResponse `protobuf:"bytes,24,opt,name=run_step_response,json=runStepResponse,proto3,oneof"`
}

type ReplayOp_CloseSessionResponse struct {
	CloseSessionResponse *CloseSessionResponse `protobuf:"bytes,25,opt,name=close_session_response,json=closeSessionResponse,proto3,oneof"`
}

type ReplayOp_ListDevicesResponse struct {
	ListDevicesResponse *ListDevicesResponse `protobuf:"bytes,26,opt,name=list_devices_response,json=listDevicesResponse,proto3,oneof"`
}

type ReplayOp_ResetRequestResponse struct {
	ResetRequestResponse *ResetResponse `protobuf:"bytes,27,opt,name=reset_request_response,json=resetRequestResponse,proto3,oneof"`
}

type ReplayOp_MakeCallableResponse struct {
	MakeCallableResponse *MakeCallableResponse `protobuf:"bytes,28,opt,name=make_callable_response,json=makeCallableResponse,proto3,oneof"`
}

type ReplayOp_RunCallableResponse struct {
	RunCallableResponse *RunCallableResponse `protobuf:"bytes,29,opt,name=run_callable_response,json=runCallableResponse,proto3,oneof"`
}

type ReplayOp_ReleaseCallableResponse struct {
	ReleaseCallableResponse *ReleaseCallableResponse `protobuf:"bytes,30,opt,name=release_callable_response,json=releaseCallableResponse,proto3,oneof"`
}

func (*ReplayOp_CreateSessionResponse) isReplayOp_Response() {}

func (*ReplayOp_ExtendSessionResponse) isReplayOp_Response() {}

func (*ReplayOp_PartialRunSetupResponse) isReplayOp_Response() {}

func (*ReplayOp_RunStepResponse) isReplayOp_Response() {}

func (*ReplayOp_CloseSessionResponse) isReplayOp_Response() {}

func (*ReplayOp_ListDevicesResponse) isReplayOp_Response() {}

func (*ReplayOp_ResetRequestResponse) isReplayOp_Response() {}

func (*ReplayOp_MakeCallableResponse) isReplayOp_Response() {}

func (*ReplayOp_RunCallableResponse) isReplayOp_Response() {}

func (*ReplayOp_ReleaseCallableResponse) isReplayOp_Response() {}

func (m *ReplayOp) GetResponse() isReplayOp_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ReplayOp) GetCreateSessionResponse() *CreateSessionResponse {
	if x, ok := m.GetResponse().(*ReplayOp_CreateSessionResponse); ok {
		return x.CreateSessionResponse
	}
	return nil
}

func (m *ReplayOp) GetExtendSessionResponse() *ExtendSessionResponse {
	if x, ok := m.GetResponse().(*ReplayOp_ExtendSessionResponse); ok {
		return x.ExtendSessionResponse
	}
	return nil
}

func (m *ReplayOp) GetPartialRunSetupResponse() *PartialRunSetupResponse {
	if x, ok := m.GetResponse().(*ReplayOp_PartialRunSetupResponse); ok {
		return x.PartialRunSetupResponse
	}
	return nil
}

func (m *ReplayOp) GetRunStepResponse() *RunStepResponse {
	if x, ok := m.GetResponse().(*ReplayOp_RunStepResponse); ok {
		return x.RunStepResponse
	}
	return nil
}

func (m *ReplayOp) GetCloseSessionResponse() *CloseSessionResponse {
	if x, ok := m.GetResponse().(*ReplayOp_CloseSessionResponse); ok {
		return x.CloseSessionResponse
	}
	return nil
}

func (m *ReplayOp) GetListDevicesResponse() *ListDevicesResponse {
	if x, ok := m.GetResponse().(*ReplayOp_ListDevicesResponse); ok {
		return x.ListDevicesResponse
	}
	return nil
}

func (m *ReplayOp) GetResetRequestResponse() *ResetResponse {
	if x, ok := m.GetResponse().(*ReplayOp_ResetRequestResponse); ok {
		return x.ResetRequestResponse
	}
	return nil
}

func (m *ReplayOp) GetMakeCallableResponse() *MakeCallableResponse {
	if x, ok := m.GetResponse().(*ReplayOp_MakeCallableResponse); ok {
		return x.MakeCallableResponse
	}
	return nil
}

func (m *ReplayOp) GetRunCallableResponse() *RunCallableResponse {
	if x, ok := m.GetResponse().(*ReplayOp_RunCallableResponse); ok {
		return x.RunCallableResponse
	}
	return nil
}

func (m *ReplayOp) GetReleaseCallableResponse() *ReleaseCallableResponse {
	if x, ok := m.GetResponse().(*ReplayOp_ReleaseCallableResponse); ok {
		return x.ReleaseCallableResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReplayOp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReplayOp_CreateSession)(nil),
		(*ReplayOp_ExtendSession)(nil),
		(*ReplayOp_PartialRunSetup)(nil),
		(*ReplayOp_RunStep)(nil),
		(*ReplayOp_CloseSession)(nil),
		(*ReplayOp_ListDevices)(nil),
		(*ReplayOp_ResetRequest)(nil),
		(*ReplayOp_MakeCallable)(nil),
		(*ReplayOp_RunCallable)(nil),
		(*ReplayOp_ReleaseCallable)(nil),
		(*ReplayOp_NewReplaySession)(nil),
		(*ReplayOp_CreateSessionResponse)(nil),
		(*ReplayOp_ExtendSessionResponse)(nil),
		(*ReplayOp_PartialRunSetupResponse)(nil),
		(*ReplayOp_RunStepResponse)(nil),
		(*ReplayOp_CloseSessionResponse)(nil),
		(*ReplayOp_ListDevicesResponse)(nil),
		(*ReplayOp_ResetRequestResponse)(nil),
		(*ReplayOp_MakeCallableResponse)(nil),
		(*ReplayOp_RunCallableResponse)(nil),
		(*ReplayOp_ReleaseCallableResponse)(nil),
	}
}

func init() {
	proto.RegisterType((*NewReplaySession)(nil), "tensorflow.NewReplaySession")
	proto.RegisterType((*ReplayOp)(nil), "tensorflow.ReplayOp")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/replay_log.proto", fileDescriptor_9ee59cdea95caad8)
}

var fileDescriptor_9ee59cdea95caad8 = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0xdd, 0x4f, 0x13, 0x4d,
	0x14, 0xc6, 0x59, 0x5e, 0x5e, 0x28, 0xa7, 0x94, 0x8f, 0x51, 0x60, 0x29, 0x08, 0xb5, 0x86, 0x04,
	0x6f, 0xda, 0x44, 0x2f, 0x8c, 0x89, 0x89, 0x91, 0xaa, 0x29, 0x09, 0x0a, 0x2e, 0x92, 0x18, 0xbd,
	0xd8, 0x6c, 0xb7, 0x07, 0xd8, 0xb0, 0x5f, 0xce, 0xcc, 0x5a, 0xfd, 0xcf, 0xbd, 0xf0, 0xc2, 0xec,
	0xec, 0x6e, 0x67, 0xa6, 0xb3, 0x10, 0xef, 0xda, 0xe7, 0x3c, 0xfb, 0x9b, 0x39, 0x67, 0xe6, 0xd9,
	0x85, 0xa7, 0x1c, 0x63, 0x96, 0xd0, 0xab, 0x30, 0x99, 0xf4, 0xfd, 0x84, 0x62, 0x3f, 0xa5, 0x09,
	0x4f, 0x46, 0xd9, 0x55, 0x9f, 0x62, 0x1a, 0x7a, 0xbf, 0xdc, 0x30, 0xb9, 0xee, 0x09, 0x8d, 0x80,
	0xb4, 0xb6, 0x0f, 0xef, 0x7c, 0x2c, 0xf2, 0x18, 0x47, 0x5a, 0x3c, 0xd2, 0xe5, 0xb0, 0xfe, 0x11,
	0x27, 0x8e, 0x20, 0x5d, 0x20, 0x63, 0x41, 0x12, 0x93, 0x97, 0xb0, 0x34, 0xc6, 0x1f, 0x81, 0x8f,
	0xcc, 0xb6, 0x3a, 0xd6, 0x51, 0xf3, 0xd9, 0x41, 0x4f, 0xc2, 0x7a, 0xa7, 0x01, 0xe3, 0x6f, 0x8b,
	0xb2, 0x83, 0x2c, 0x4d, 0x62, 0x86, 0x4e, 0xe5, 0x27, 0x87, 0xb0, 0xca, 0x0a, 0x8a, 0x7b, 0xe3,
	0xc5, 0xe3, 0x10, 0xed, 0xf9, 0x8e, 0x75, 0xb4, 0xec, 0xb4, 0x4a, 0x75, 0x28, 0xc4, 0xee, 0x9f,
	0x16, 0x34, 0x8a, 0x35, 0xcf, 0x52, 0xd2, 0x85, 0x16, 0xe3, 0x1e, 0xe5, 0x2e, 0x0f, 0x22, 0x74,
	0x33, 0x66, 0x1f, 0x74, 0xac, 0x23, 0xcb, 0x69, 0x0a, 0xf1, 0x73, 0x10, 0xe1, 0x25, 0x23, 0xfb,
	0xd0, 0xc4, 0x78, 0x3c, 0x75, 0x74, 0x84, 0x63, 0x19, 0xe3, 0x71, 0x59, 0x3f, 0x81, 0x55, 0x9f,
	0xa2, 0xc7, 0xd1, 0x2d, 0x17, 0x2a, 0x77, 0xde, 0x51, 0x77, 0x3e, 0x10, 0x8e, 0xb2, 0x4b, 0x07,
	0xbf, 0x67, 0xc8, 0xf8, 0x70, 0xce, 0x69, 0xf9, 0xaa, 0x9e, 0xa3, 0xf0, 0x27, 0xcf, 0x57, 0xab,
	0x50, 0xf3, 0x26, 0xea, 0x9d, 0x70, 0x98, 0x28, 0x54, 0x75, 0x72, 0x0e, 0x1b, 0xa9, 0x47, 0x79,
	0xe0, 0x85, 0x2e, 0xcd, 0x62, 0x97, 0x21, 0xcf, 0x52, 0xfb, 0x3f, 0x41, 0xeb, 0xaa, 0xb4, 0xf3,
	0xc2, 0xe4, 0x64, 0xf1, 0x45, 0x6e, 0x91, 0xbc, 0xb5, 0x54, 0xaf, 0x90, 0x17, 0xd0, 0x10, 0x24,
	0x8e, 0xa9, 0xbd, 0x20, 0x40, 0x6d, 0x15, 0x94, 0xfb, 0x38, 0x2a, 0x80, 0x25, 0x5a, 0x28, 0xe4,
	0x3d, 0xb4, 0xfc, 0x30, 0x61, 0x72, 0x3e, 0xff, 0x9b, 0x27, 0x3b, 0xc8, 0x0d, 0x46, 0x4f, 0x2b,
	0xbe, 0x22, 0x93, 0x01, 0xac, 0x84, 0x01, 0xe3, 0x6e, 0x75, 0x41, 0x16, 0x05, 0x66, 0xff, 0xce,
	0x0b, 0x52, 0x51, 0x9a, 0xa1, 0x54, 0xc9, 0x6b, 0x68, 0x51, 0x64, 0xc8, 0x5d, 0x5a, 0xd4, 0xed,
	0x25, 0x41, 0xb1, 0xb5, 0x56, 0x72, 0x83, 0xb2, 0x0b, 0xaa, 0xfc, 0xcf, 0xbb, 0x89, 0xbc, 0x5b,
	0x74, 0x7d, 0x2f, 0x0c, 0xbd, 0x51, 0x88, 0x76, 0xc3, 0xec, 0xe6, 0x83, 0x77, 0x8b, 0x83, 0xb2,
	0xae, 0x70, 0x22, 0x45, 0xce, 0xbb, 0xc9, 0xc7, 0x39, 0xc5, 0x2c, 0x9b, 0xdd, 0x38, 0x59, 0x6c,
	0x52, 0x9a, 0x54, 0xaa, 0xe4, 0x0c, 0xd6, 0x29, 0x86, 0xe8, 0x31, 0x65, 0x3f, 0x60, 0x1e, 0xb2,
	0x53, 0x78, 0x4c, 0xd8, 0x1a, 0xd5, 0x2b, 0xe4, 0x14, 0x48, 0x8c, 0x13, 0xb7, 0x8c, 0x77, 0x75,
	0x60, 0x4d, 0x81, 0xdc, 0x53, 0x91, 0xb3, 0xc9, 0x1d, 0xce, 0x39, 0xeb, 0xf1, 0x6c, 0x9a, 0xbf,
	0xc1, 0xb6, 0x1e, 0x0d, 0x97, 0x96, 0xb1, 0xb5, 0x37, 0x05, 0xf2, 0xf1, 0x3d, 0x19, 0x29, 0x8c,
	0x43, 0xcb, 0xd9, 0xf4, 0xeb, 0x0a, 0x39, 0x5c, 0x0f, 0x8b, 0x84, 0x6f, 0x99, 0xf0, 0x99, 0xd4,
	0x48, 0x38, 0xd6, 0x15, 0xc8, 0x08, 0xda, 0x46, 0x7c, 0x24, 0x7f, 0x5b, 0xf0, 0x9f, 0xdc, 0x9b,
	0xa3, 0xe9, 0x0a, 0xdb, 0x69, 0x7d, 0x89, 0x9c, 0xc0, 0x46, 0x15, 0x28, 0x89, 0xb6, 0x05, 0x7a,
	0xb7, 0x36, 0x59, 0x53, 0xe4, 0x1a, 0xd5, 0x25, 0xf2, 0x05, 0xb6, 0xb4, 0x88, 0x49, 0xde, 0x4e,
	0xcd, 0xbb, 0x48, 0xcb, 0xda, 0x14, 0xfa, 0xd0, 0xaf, 0xd1, 0xc9, 0x25, 0x6c, 0xaa, 0xa1, 0x93,
	0xe0, 0xf6, 0x3f, 0xbd, 0x9e, 0x87, 0x96, 0xf3, 0x20, 0x34, 0x65, 0xf2, 0x09, 0xb6, 0xb4, 0x18,
	0x4a, 0xee, 0xae, 0xe0, 0xee, 0xd4, 0xe4, 0x51, 0xee, 0x54, 0x0d, 0xa4, 0x3a, 0x03, 0x2d, 0x98,
	0x12, 0xb9, 0x67, 0xce, 0x40, 0x4f, 0xa8, 0x24, 0x47, 0x35, 0x7a, 0x3e, 0x03, 0x35, 0xaa, 0x12,
	0xfc, 0xc8, 0x9c, 0x81, 0x96, 0x59, 0x39, 0x03, 0x6a, 0xca, 0xc4, 0x83, 0x9d, 0xd9, 0xf0, 0x4a,
	0xf4, 0xbe, 0x79, 0xc5, 0x8c, 0x14, 0xcb, 0x2b, 0x46, 0xeb, 0x4b, 0xc7, 0x0b, 0x30, 0x9f, 0xa4,
	0xc7, 0x00, 0x8d, 0x8a, 0x7b, 0xfc, 0xe6, 0xeb, 0xab, 0xeb, 0x80, 0xdf, 0x64, 0xa3, 0x9e, 0x9f,
	0x44, 0x7d, 0xe5, 0x43, 0x5d, 0xff, 0xf3, 0x3a, 0xd1, 0xbf, 0xe0, 0xbf, 0x2d, 0x6b, 0xb4, 0x28,
	0xfe, 0x3c, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xe8, 0x2f, 0xcc, 0x1e, 0x08, 0x00, 0x00,
}
