// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/contrib/cloud/kernels/bigquery_table_partition.proto

package cloud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This proto specifies a table partition in BigQuery.
type BigQueryTablePartition struct {
	// [start_index, end_index] specify the boundaries of a partition.
	// If end_index is -1, every row starting from start_index is part of the
	// partition.
	StartIndex           int64    `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	EndIndex             int64    `protobuf:"varint,2,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigQueryTablePartition) Reset()         { *m = BigQueryTablePartition{} }
func (m *BigQueryTablePartition) String() string { return proto.CompactTextString(m) }
func (*BigQueryTablePartition) ProtoMessage()    {}
func (*BigQueryTablePartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_140962adb356b896, []int{0}
}

func (m *BigQueryTablePartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigQueryTablePartition.Unmarshal(m, b)
}
func (m *BigQueryTablePartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigQueryTablePartition.Marshal(b, m, deterministic)
}
func (m *BigQueryTablePartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigQueryTablePartition.Merge(m, src)
}
func (m *BigQueryTablePartition) XXX_Size() int {
	return xxx_messageInfo_BigQueryTablePartition.Size(m)
}
func (m *BigQueryTablePartition) XXX_DiscardUnknown() {
	xxx_messageInfo_BigQueryTablePartition.DiscardUnknown(m)
}

var xxx_messageInfo_BigQueryTablePartition proto.InternalMessageInfo

func (m *BigQueryTablePartition) GetStartIndex() int64 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *BigQueryTablePartition) GetEndIndex() int64 {
	if m != nil {
		return m.EndIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*BigQueryTablePartition)(nil), "tensorflow.BigQueryTablePartition")
}

func init() {
	proto.RegisterFile("tensorflow/contrib/cloud/kernels/bigquery_table_partition.proto", fileDescriptor_140962adb356b896)
}

var fileDescriptor_140962adb356b896 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x2f, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0xd7, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0x4c, 0xd2, 0x4f,
	0xce, 0xc9, 0x2f, 0x4d, 0xd1, 0xcf, 0x4e, 0x2d, 0xca, 0x4b, 0xcd, 0x29, 0xd6, 0x4f, 0xca, 0x4c,
	0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0x8c, 0x2f, 0x49, 0x4c, 0xca, 0x49, 0x8d, 0x2f, 0x48, 0x2c, 0x2a,
	0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x18, 0xa0,
	0x14, 0xc6, 0x25, 0xe6, 0x94, 0x99, 0x1e, 0x08, 0x52, 0x1d, 0x02, 0x52, 0x1c, 0x00, 0x53, 0x2b,
	0x24, 0xcf, 0xc5, 0x5d, 0x5c, 0x92, 0x58, 0x54, 0x12, 0x9f, 0x99, 0x97, 0x92, 0x5a, 0x21, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x05, 0x16, 0xf2, 0x04, 0x89, 0x08, 0x49, 0x73, 0x71, 0xa6,
	0xe6, 0xa5, 0x40, 0xa5, 0x99, 0xc0, 0xd2, 0x1c, 0xa9, 0x79, 0x29, 0x60, 0x49, 0x27, 0xe7, 0x28,
	0xc7, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x24, 0x17, 0x63, 0x67,
	0xa6, 0xe7, 0xeb, 0x27, 0xe7, 0x17, 0xa5, 0xa2, 0xfa, 0x27, 0x89, 0x0d, 0xec, 0x5e, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x35, 0x76, 0x91, 0xf2, 0x00, 0x00, 0x00,
}
