// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/profiler/op_profile.proto

package profiler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Profile is the top-level data that summarizes a program.
type Profile struct {
	// Root of a profile broken down by instruction category.
	ByCategory *Node `protobuf:"bytes,1,opt,name=by_category,json=byCategory,proto3" json:"by_category,omitempty"`
	// Root of a profile broken down by program.
	ByProgram            *Node    `protobuf:"bytes,4,opt,name=by_program,json=byProgram,proto3" json:"by_program,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetByCategory() *Node {
	if m != nil {
		return m.ByCategory
	}
	return nil
}

func (m *Profile) GetByProgram() *Node {
	if m != nil {
		return m.ByProgram
	}
	return nil
}

// An entry in the profile tree. (An instruction, or set of instructions).
type Node struct {
	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metrics  *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Children []*Node  `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	// Details about what this node represents.
	//
	// Types that are valid to be assigned to Contents:
	//	*Node_Category
	//	*Node_Xla
	Contents             isNode_Contents `protobuf_oneof:"contents"`
	NumChildren          int32           `protobuf:"varint,6,opt,name=num_children,json=numChildren,proto3" json:"num_children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetMetrics() *Metrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Node) GetChildren() []*Node {
	if m != nil {
		return m.Children
	}
	return nil
}

type isNode_Contents interface {
	isNode_Contents()
}

type Node_Category struct {
	Category *Node_InstructionCategory `protobuf:"bytes,4,opt,name=category,proto3,oneof"`
}

type Node_Xla struct {
	Xla *Node_XLAInstruction `protobuf:"bytes,5,opt,name=xla,proto3,oneof"`
}

func (*Node_Category) isNode_Contents() {}

func (*Node_Xla) isNode_Contents() {}

func (m *Node) GetContents() isNode_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Node) GetCategory() *Node_InstructionCategory {
	if x, ok := m.GetContents().(*Node_Category); ok {
		return x.Category
	}
	return nil
}

func (m *Node) GetXla() *Node_XLAInstruction {
	if x, ok := m.GetContents().(*Node_Xla); ok {
		return x.Xla
	}
	return nil
}

func (m *Node) GetNumChildren() int32 {
	if m != nil {
		return m.NumChildren
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Node) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Node_Category)(nil),
		(*Node_Xla)(nil),
	}
}

// A category of XLA instructions.
// name is a descriptive string, like "data formatting".
type Node_InstructionCategory struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node_InstructionCategory) Reset()         { *m = Node_InstructionCategory{} }
func (m *Node_InstructionCategory) String() string { return proto.CompactTextString(m) }
func (*Node_InstructionCategory) ProtoMessage()    {}
func (*Node_InstructionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{1, 0}
}

func (m *Node_InstructionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node_InstructionCategory.Unmarshal(m, b)
}
func (m *Node_InstructionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node_InstructionCategory.Marshal(b, m, deterministic)
}
func (m *Node_InstructionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node_InstructionCategory.Merge(m, src)
}
func (m *Node_InstructionCategory) XXX_Size() int {
	return xxx_messageInfo_Node_InstructionCategory.Size(m)
}
func (m *Node_InstructionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_Node_InstructionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_Node_InstructionCategory proto.InternalMessageInfo

// A single XLA instruction.
// name is the unique instruction id, like "%multiply.5".
type Node_XLAInstruction struct {
	Op         string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Expression string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Provenance string `protobuf:"bytes,3,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Category   string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Describes the physical memory layout of the instruction's primary input.
	// e.g. for a convolution, this analyzes the image and ignores the kernel.
	Layout               *Node_XLAInstruction_LayoutAnalysis `protobuf:"bytes,5,opt,name=layout,proto3" json:"layout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Node_XLAInstruction) Reset()         { *m = Node_XLAInstruction{} }
func (m *Node_XLAInstruction) String() string { return proto.CompactTextString(m) }
func (*Node_XLAInstruction) ProtoMessage()    {}
func (*Node_XLAInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{1, 1}
}

func (m *Node_XLAInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node_XLAInstruction.Unmarshal(m, b)
}
func (m *Node_XLAInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node_XLAInstruction.Marshal(b, m, deterministic)
}
func (m *Node_XLAInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node_XLAInstruction.Merge(m, src)
}
func (m *Node_XLAInstruction) XXX_Size() int {
	return xxx_messageInfo_Node_XLAInstruction.Size(m)
}
func (m *Node_XLAInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Node_XLAInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_Node_XLAInstruction proto.InternalMessageInfo

func (m *Node_XLAInstruction) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Node_XLAInstruction) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Node_XLAInstruction) GetProvenance() string {
	if m != nil {
		return m.Provenance
	}
	return ""
}

func (m *Node_XLAInstruction) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Node_XLAInstruction) GetLayout() *Node_XLAInstruction_LayoutAnalysis {
	if m != nil {
		return m.Layout
	}
	return nil
}

type Node_XLAInstruction_LayoutAnalysis struct {
	// The physical data layout, from most-minor to most-major dimensions.
	Dimensions           []*Node_XLAInstruction_LayoutAnalysis_Dimension `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *Node_XLAInstruction_LayoutAnalysis) Reset()         { *m = Node_XLAInstruction_LayoutAnalysis{} }
func (m *Node_XLAInstruction_LayoutAnalysis) String() string { return proto.CompactTextString(m) }
func (*Node_XLAInstruction_LayoutAnalysis) ProtoMessage()    {}
func (*Node_XLAInstruction_LayoutAnalysis) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{1, 1, 0}
}

func (m *Node_XLAInstruction_LayoutAnalysis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis.Unmarshal(m, b)
}
func (m *Node_XLAInstruction_LayoutAnalysis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis.Marshal(b, m, deterministic)
}
func (m *Node_XLAInstruction_LayoutAnalysis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis.Merge(m, src)
}
func (m *Node_XLAInstruction_LayoutAnalysis) XXX_Size() int {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis.Size(m)
}
func (m *Node_XLAInstruction_LayoutAnalysis) XXX_DiscardUnknown() {
	xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis.DiscardUnknown(m)
}

var xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis proto.InternalMessageInfo

func (m *Node_XLAInstruction_LayoutAnalysis) GetDimensions() []*Node_XLAInstruction_LayoutAnalysis_Dimension {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

type Node_XLAInstruction_LayoutAnalysis_Dimension struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Alignment            int32    `protobuf:"varint,2,opt,name=alignment,proto3" json:"alignment,omitempty"`
	Semantics            string   `protobuf:"bytes,3,opt,name=semantics,proto3" json:"semantics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) Reset() {
	*m = Node_XLAInstruction_LayoutAnalysis_Dimension{}
}
func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) String() string {
	return proto.CompactTextString(m)
}
func (*Node_XLAInstruction_LayoutAnalysis_Dimension) ProtoMessage() {}
func (*Node_XLAInstruction_LayoutAnalysis_Dimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{1, 1, 0, 0}
}

func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension.Unmarshal(m, b)
}
func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension.Marshal(b, m, deterministic)
}
func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension.Merge(m, src)
}
func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) XXX_Size() int {
	return xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension.Size(m)
}
func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) XXX_DiscardUnknown() {
	xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension.DiscardUnknown(m)
}

var xxx_messageInfo_Node_XLAInstruction_LayoutAnalysis_Dimension proto.InternalMessageInfo

func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) GetAlignment() int32 {
	if m != nil {
		return m.Alignment
	}
	return 0
}

func (m *Node_XLAInstruction_LayoutAnalysis_Dimension) GetSemantics() string {
	if m != nil {
		return m.Semantics
	}
	return ""
}

// Measurements of an operation (or aggregated set of operations).
// Metrics are always "total" rather than "self".
type Metrics struct {
	// Core-time taken by this operation, as a fraction of all operations.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// Floating point computations performed by this operation, as a fraction of
	// peak core FLOPS * program time. This representation has useful properties:
	//  - it is proportional to the number of floating point operations performed
	//  - utilization is flops/time
	//  - wasted potential flops is proportional to time - flops
	//  - it does not reveal the peak core FLOPS of the hardware
	Flops float64 `protobuf:"fixed64,2,opt,name=flops,proto3" json:"flops,omitempty"`
	// The memory bandwidth used to load operands, as a fraction of
	// thereotical memory bandwidth on the specific hardware.
	MemoryBandwidth      float64  `protobuf:"fixed64,3,opt,name=memory_bandwidth,json=memoryBandwidth,proto3" json:"memory_bandwidth,omitempty"`
	RawTime              float64  `protobuf:"fixed64,11,opt,name=raw_time,json=rawTime,proto3" json:"raw_time,omitempty"`
	RawFlops             float64  `protobuf:"fixed64,12,opt,name=raw_flops,json=rawFlops,proto3" json:"raw_flops,omitempty"`
	RawBytesAccessed     float64  `protobuf:"fixed64,13,opt,name=raw_bytes_accessed,json=rawBytesAccessed,proto3" json:"raw_bytes_accessed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6543240768c2a32, []int{2}
}

func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Metrics) GetFlops() float64 {
	if m != nil {
		return m.Flops
	}
	return 0
}

func (m *Metrics) GetMemoryBandwidth() float64 {
	if m != nil {
		return m.MemoryBandwidth
	}
	return 0
}

func (m *Metrics) GetRawTime() float64 {
	if m != nil {
		return m.RawTime
	}
	return 0
}

func (m *Metrics) GetRawFlops() float64 {
	if m != nil {
		return m.RawFlops
	}
	return 0
}

func (m *Metrics) GetRawBytesAccessed() float64 {
	if m != nil {
		return m.RawBytesAccessed
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "tensorflow.profiler.op_profile.Profile")
	proto.RegisterType((*Node)(nil), "tensorflow.profiler.op_profile.Node")
	proto.RegisterType((*Node_InstructionCategory)(nil), "tensorflow.profiler.op_profile.Node.InstructionCategory")
	proto.RegisterType((*Node_XLAInstruction)(nil), "tensorflow.profiler.op_profile.Node.XLAInstruction")
	proto.RegisterType((*Node_XLAInstruction_LayoutAnalysis)(nil), "tensorflow.profiler.op_profile.Node.XLAInstruction.LayoutAnalysis")
	proto.RegisterType((*Node_XLAInstruction_LayoutAnalysis_Dimension)(nil), "tensorflow.profiler.op_profile.Node.XLAInstruction.LayoutAnalysis.Dimension")
	proto.RegisterType((*Metrics)(nil), "tensorflow.profiler.op_profile.Metrics")
}

func init() {
	proto.RegisterFile("tensorflow/core/profiler/op_profile.proto", fileDescriptor_f6543240768c2a32)
}

var fileDescriptor_f6543240768c2a32 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0xa6, 0xed, 0x9a, 0xd3, 0x31, 0x2a, 0x33, 0xa4, 0x50, 0xd0, 0x34, 0x26, 0x24,
	0x36, 0x09, 0xa5, 0x12, 0xbb, 0xe1, 0x92, 0xb6, 0xfc, 0x19, 0xd3, 0x40, 0x93, 0x85, 0x10, 0x1a,
	0x17, 0x91, 0x93, 0x7a, 0x9d, 0xa5, 0xc4, 0x8e, 0x6c, 0x97, 0x2e, 0x3c, 0x18, 0xb7, 0xdc, 0xf0,
	0x16, 0xbc, 0x0c, 0xb2, 0x9d, 0x36, 0x1d, 0x9a, 0xa0, 0xc0, 0xdd, 0xe9, 0xf9, 0x8e, 0x7f, 0x3e,
	0xfe, 0x7a, 0x72, 0xe0, 0x50, 0x53, 0xae, 0x84, 0xbc, 0xc8, 0xc4, 0x7c, 0x90, 0x0a, 0x49, 0x07,
	0x85, 0x14, 0x17, 0x2c, 0xa3, 0x72, 0x20, 0x8a, 0xb8, 0x8a, 0xa3, 0x42, 0x0a, 0x2d, 0xd0, 0x6e,
	0x5d, 0x1a, 0x2d, 0xaa, 0xa2, 0xba, 0x6a, 0xff, 0xbb, 0x07, 0x9b, 0x67, 0x2e, 0x46, 0x2f, 0xa1,
	0x9b, 0x94, 0x71, 0x4a, 0x34, 0x9d, 0x0a, 0x59, 0x86, 0xde, 0x9e, 0x77, 0xd0, 0x7d, 0xfa, 0x28,
	0xfa, 0x3d, 0x21, 0x7a, 0x27, 0x26, 0x14, 0x43, 0x52, 0x8e, 0xab, 0x73, 0x68, 0x0c, 0x90, 0x94,
	0x46, 0x9e, 0x4a, 0x92, 0x87, 0xcd, 0xbf, 0xa0, 0x04, 0x49, 0x79, 0xe6, 0x8e, 0x9d, 0x34, 0x3b,
	0x8d, 0x9e, 0x7f, 0xd2, 0xec, 0xf8, 0xbd, 0x26, 0xde, 0xa9, 0x71, 0xb1, 0xd2, 0x72, 0x96, 0xea,
	0x99, 0xa4, 0xb8, 0x5b, 0x50, 0xb9, 0x48, 0xef, 0x7f, 0x6b, 0x43, 0xd3, 0x20, 0x10, 0x82, 0x26,
	0x27, 0x39, 0xb5, 0xcd, 0x07, 0xd8, 0xc6, 0x68, 0x08, 0x9b, 0x39, 0xd5, 0x92, 0xa5, 0x2a, 0x6c,
	0xd8, 0x6e, 0x1e, 0xff, 0xa9, 0x9b, 0xb7, 0xae, 0x1c, 0x2f, 0xce, 0xa1, 0xe7, 0xd0, 0x49, 0x2f,
	0x59, 0x36, 0x91, 0x94, 0x87, 0xfe, 0x9e, 0xbf, 0xf6, 0x8b, 0x96, 0xa7, 0xd0, 0x07, 0xe8, 0x2c,
	0x9d, 0x75, 0x9e, 0x3c, 0x5b, 0x87, 0x10, 0xbd, 0xe1, 0xee, 0xc9, 0x4c, 0xf0, 0x85, 0xc3, 0xc7,
	0x1b, 0x78, 0xc9, 0x42, 0xaf, 0xc1, 0xbf, 0xca, 0x48, 0xd8, 0xb2, 0xc8, 0xa3, 0xb5, 0x90, 0x1f,
	0x4f, 0x87, 0x2b, 0xd4, 0xe3, 0x0d, 0x6c, 0x08, 0xe8, 0x21, 0x6c, 0xf1, 0x59, 0x1e, 0x2f, 0x9f,
	0xd9, 0xde, 0xf3, 0x0e, 0x5a, 0xb8, 0xcb, 0x67, 0xf9, 0xb8, 0x4a, 0xf5, 0xef, 0xc2, 0x9d, 0x1b,
	0xda, 0xe9, 0x7f, 0xf5, 0x61, 0xfb, 0x3a, 0x13, 0x6d, 0x43, 0x43, 0x14, 0xd5, 0x9f, 0xd0, 0x10,
	0x05, 0xda, 0x05, 0xa0, 0x57, 0x85, 0xa4, 0x4a, 0x31, 0xc1, 0xed, 0xbf, 0x10, 0xe0, 0x95, 0x8c,
	0xd1, 0x0b, 0x29, 0x3e, 0x53, 0x4e, 0x78, 0x4a, 0x43, 0xdf, 0xe9, 0x75, 0x06, 0xf5, 0x7f, 0x71,
	0x2f, 0x58, 0x71, 0xe0, 0x1c, 0xda, 0x19, 0x29, 0xc5, 0x4c, 0x57, 0x26, 0x8c, 0xfe, 0xc1, 0x84,
	0xe8, 0xd4, 0x12, 0x86, 0x9c, 0x64, 0xa5, 0x62, 0x0a, 0x57, 0xc4, 0xfe, 0x0f, 0x0f, 0xb6, 0xaf,
	0x4b, 0x28, 0x03, 0x98, 0xb0, 0x9c, 0x72, 0xd3, 0xb7, 0x0a, 0x3d, 0x3b, 0x0c, 0xa7, 0xff, 0x7f,
	0x65, 0xf4, 0x62, 0x01, 0xc5, 0x2b, 0xfc, 0xfe, 0x27, 0x08, 0x96, 0x82, 0x19, 0x6e, 0xc5, 0xbe,
	0xb8, 0xe1, 0x6e, 0x61, 0x1b, 0xa3, 0x07, 0x10, 0x90, 0x8c, 0x4d, 0x79, 0x4e, 0xb9, 0xb6, 0xc6,
	0xb6, 0x70, 0x9d, 0x30, 0xaa, 0xa2, 0x39, 0xe1, 0xda, 0x0c, 0xbf, 0xb3, 0xb5, 0x4e, 0x8c, 0x00,
	0x3a, 0xa9, 0xe0, 0x9a, 0x72, 0xad, 0xec, 0x22, 0xa8, 0xc6, 0xde, 0xdc, 0xa3, 0x59, 0xf5, 0x11,
	0x79, 0xd8, 0xc6, 0x68, 0x07, 0x5a, 0x17, 0x99, 0x28, 0xdc, 0x27, 0xe4, 0x61, 0xf7, 0x03, 0x1d,
	0x42, 0x2f, 0xa7, 0xb9, 0x90, 0x65, 0x9c, 0x10, 0x3e, 0x99, 0xb3, 0x89, 0xbe, 0xb4, 0xd7, 0x78,
	0xf8, 0xb6, 0xcb, 0x8f, 0x16, 0x69, 0x74, 0x0f, 0x3a, 0x92, 0xcc, 0x63, 0x0b, 0xee, 0xda, 0x92,
	0x4d, 0x49, 0xe6, 0xef, 0x0d, 0xfb, 0x3e, 0x04, 0x46, 0x72, 0xfc, 0x2d, 0xab, 0x99, 0xda, 0x57,
	0xf6, 0x8a, 0x27, 0x80, 0x8c, 0x98, 0x94, 0x9a, 0xaa, 0x98, 0xa4, 0x29, 0x55, 0x8a, 0x4e, 0xc2,
	0x5b, 0xb6, 0xaa, 0x27, 0xc9, 0x7c, 0x64, 0x84, 0x61, 0x95, 0x1f, 0x8d, 0xcf, 0x87, 0x53, 0xa6,
	0x2f, 0x67, 0x49, 0x94, 0x8a, 0x7c, 0xb0, 0xb2, 0x27, 0x6f, 0x0e, 0xa7, 0xc2, 0x2d, 0xd0, 0x6b,
	0x5b, 0x34, 0x69, 0xdb, 0xdd, 0x79, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0xba, 0x1f, 0x2d, 0xb2,
	0x68, 0x05, 0x00, 0x00,
}
