// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/profiler/tfprof_log.proto

package profiler

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	framework "github.com/tensorflow/tensorflow/tensorflow/go/core/framework"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// It specifies the Python callstack that creates an op.
type CodeDef struct {
	Traces               []*CodeDef_Trace `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CodeDef) Reset()         { *m = CodeDef{} }
func (m *CodeDef) String() string { return proto.CompactTextString(m) }
func (*CodeDef) ProtoMessage()    {}
func (*CodeDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{0}
}

func (m *CodeDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeDef.Unmarshal(m, b)
}
func (m *CodeDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeDef.Marshal(b, m, deterministic)
}
func (m *CodeDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeDef.Merge(m, src)
}
func (m *CodeDef) XXX_Size() int {
	return xxx_messageInfo_CodeDef.Size(m)
}
func (m *CodeDef) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeDef.DiscardUnknown(m)
}

var xxx_messageInfo_CodeDef proto.InternalMessageInfo

func (m *CodeDef) GetTraces() []*CodeDef_Trace {
	if m != nil {
		return m.Traces
	}
	return nil
}

type CodeDef_Trace struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"` // Deprecated: Do not use.
	FileId               int64    `protobuf:"varint,6,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Lineno               int32    `protobuf:"varint,2,opt,name=lineno,proto3" json:"lineno,omitempty"`
	Function             string   `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"` // Deprecated: Do not use.
	FunctionId           int64    `protobuf:"varint,7,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Line                 string   `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"` // Deprecated: Do not use.
	LineId               int64    `protobuf:"varint,8,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	FuncStartLine        int32    `protobuf:"varint,5,opt,name=func_start_line,json=funcStartLine,proto3" json:"func_start_line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeDef_Trace) Reset()         { *m = CodeDef_Trace{} }
func (m *CodeDef_Trace) String() string { return proto.CompactTextString(m) }
func (*CodeDef_Trace) ProtoMessage()    {}
func (*CodeDef_Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{0, 0}
}

func (m *CodeDef_Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeDef_Trace.Unmarshal(m, b)
}
func (m *CodeDef_Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeDef_Trace.Marshal(b, m, deterministic)
}
func (m *CodeDef_Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeDef_Trace.Merge(m, src)
}
func (m *CodeDef_Trace) XXX_Size() int {
	return xxx_messageInfo_CodeDef_Trace.Size(m)
}
func (m *CodeDef_Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeDef_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_CodeDef_Trace proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *CodeDef_Trace) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *CodeDef_Trace) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *CodeDef_Trace) GetLineno() int32 {
	if m != nil {
		return m.Lineno
	}
	return 0
}

// Deprecated: Do not use.
func (m *CodeDef_Trace) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *CodeDef_Trace) GetFunctionId() int64 {
	if m != nil {
		return m.FunctionId
	}
	return 0
}

// Deprecated: Do not use.
func (m *CodeDef_Trace) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *CodeDef_Trace) GetLineId() int64 {
	if m != nil {
		return m.LineId
	}
	return 0
}

func (m *CodeDef_Trace) GetFuncStartLine() int32 {
	if m != nil {
		return m.FuncStartLine
	}
	return 0
}

type OpLogEntry struct {
	// op name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// float_ops is filled by tfprof Python API when called. It requires the
	// op has RegisterStatistics defined. Currently, Conv2D, MatMul, etc, are
	// implemented.
	FloatOps int64 `protobuf:"varint,2,opt,name=float_ops,json=floatOps,proto3" json:"float_ops,omitempty"`
	// User can define extra op type information for an op. This allows the user
	// to select a group of ops precisely using op_type as a key.
	Types []string `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	// Used to support tfprof "code" view.
	CodeDef              *CodeDef `protobuf:"bytes,4,opt,name=code_def,json=codeDef,proto3" json:"code_def,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpLogEntry) Reset()         { *m = OpLogEntry{} }
func (m *OpLogEntry) String() string { return proto.CompactTextString(m) }
func (*OpLogEntry) ProtoMessage()    {}
func (*OpLogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{1}
}

func (m *OpLogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpLogEntry.Unmarshal(m, b)
}
func (m *OpLogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpLogEntry.Marshal(b, m, deterministic)
}
func (m *OpLogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpLogEntry.Merge(m, src)
}
func (m *OpLogEntry) XXX_Size() int {
	return xxx_messageInfo_OpLogEntry.Size(m)
}
func (m *OpLogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OpLogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OpLogEntry proto.InternalMessageInfo

func (m *OpLogEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpLogEntry) GetFloatOps() int64 {
	if m != nil {
		return m.FloatOps
	}
	return 0
}

func (m *OpLogEntry) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *OpLogEntry) GetCodeDef() *CodeDef {
	if m != nil {
		return m.CodeDef
	}
	return nil
}

type OpLogProto struct {
	LogEntries []*OpLogEntry `protobuf:"bytes,1,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	// Maps from id of CodeDef file,function,line to its string
	// In the future can also map other id of other fields to string.
	IdToString           map[int64]string `protobuf:"bytes,2,rep,name=id_to_string,json=idToString,proto3" json:"id_to_string,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OpLogProto) Reset()         { *m = OpLogProto{} }
func (m *OpLogProto) String() string { return proto.CompactTextString(m) }
func (*OpLogProto) ProtoMessage()    {}
func (*OpLogProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{2}
}

func (m *OpLogProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpLogProto.Unmarshal(m, b)
}
func (m *OpLogProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpLogProto.Marshal(b, m, deterministic)
}
func (m *OpLogProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpLogProto.Merge(m, src)
}
func (m *OpLogProto) XXX_Size() int {
	return xxx_messageInfo_OpLogProto.Size(m)
}
func (m *OpLogProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OpLogProto.DiscardUnknown(m)
}

var xxx_messageInfo_OpLogProto proto.InternalMessageInfo

func (m *OpLogProto) GetLogEntries() []*OpLogEntry {
	if m != nil {
		return m.LogEntries
	}
	return nil
}

func (m *OpLogProto) GetIdToString() map[int64]string {
	if m != nil {
		return m.IdToString
	}
	return nil
}

// A proto representation of the profiler's profile.
// It allows serialization, shipping around and deserialization of the profiles.
//
// Please don't depend on the internals of the profile proto.
type ProfileProto struct {
	Nodes map[int64]*ProfileNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Whether or not has code traces.
	HasTrace bool `protobuf:"varint,2,opt,name=has_trace,json=hasTrace,proto3" json:"has_trace,omitempty"`
	// Whether or not the TF device tracer fails to return accelerator
	// information (which could lead to 0 accelerator execution time).
	MissAcceleratorStream bool `protobuf:"varint,5,opt,name=miss_accelerator_stream,json=missAcceleratorStream,proto3" json:"miss_accelerator_stream,omitempty"`
	// Traced steps.
	Steps []int64 `protobuf:"varint,3,rep,packed,name=steps,proto3" json:"steps,omitempty"`
	// Maps from id of CodeDef file,function,line to its string
	// In the future can also map other id of other fields to string.
	IdToString           map[int64]string `protobuf:"bytes,4,rep,name=id_to_string,json=idToString,proto3" json:"id_to_string,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProfileProto) Reset()         { *m = ProfileProto{} }
func (m *ProfileProto) String() string { return proto.CompactTextString(m) }
func (*ProfileProto) ProtoMessage()    {}
func (*ProfileProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{3}
}

func (m *ProfileProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileProto.Unmarshal(m, b)
}
func (m *ProfileProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileProto.Marshal(b, m, deterministic)
}
func (m *ProfileProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileProto.Merge(m, src)
}
func (m *ProfileProto) XXX_Size() int {
	return xxx_messageInfo_ProfileProto.Size(m)
}
func (m *ProfileProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileProto proto.InternalMessageInfo

func (m *ProfileProto) GetNodes() map[int64]*ProfileNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ProfileProto) GetHasTrace() bool {
	if m != nil {
		return m.HasTrace
	}
	return false
}

func (m *ProfileProto) GetMissAcceleratorStream() bool {
	if m != nil {
		return m.MissAcceleratorStream
	}
	return false
}

func (m *ProfileProto) GetSteps() []int64 {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *ProfileProto) GetIdToString() map[int64]string {
	if m != nil {
		return m.IdToString
	}
	return nil
}

type ProfileNode struct {
	// graph node name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// graph operation type.
	Op string `protobuf:"bytes,9,opt,name=op,proto3" json:"op,omitempty"`
	// A unique id for the node.
	Id           int64            `protobuf:"varint,13,opt,name=id,proto3" json:"id,omitempty"`
	Inputs       map[int32]int64  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	InputShapes  map[int32]*Tuple `protobuf:"bytes,16,rep,name=input_shapes,json=inputShapes,proto3" json:"input_shapes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Outputs      map[int32]int64  `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	OutputShapes map[int32]*Tuple `protobuf:"bytes,15,rep,name=output_shapes,json=outputShapes,proto3" json:"output_shapes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// A map from source node id to its output index to current node.
	SrcOutputIndex       map[int64]int32                 `protobuf:"bytes,14,rep,name=src_output_index,json=srcOutputIndex,proto3" json:"src_output_index,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Shape                []int64                         `protobuf:"varint,4,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	OpTypes              []string                        `protobuf:"bytes,5,rep,name=op_types,json=opTypes,proto3" json:"op_types,omitempty"`
	CanonicalDevice      string                          `protobuf:"bytes,6,opt,name=canonical_device,json=canonicalDevice,proto3" json:"canonical_device,omitempty"`
	HostDevice           string                          `protobuf:"bytes,7,opt,name=host_device,json=hostDevice,proto3" json:"host_device,omitempty"`
	FloatOps             int64                           `protobuf:"varint,8,opt,name=float_ops,json=floatOps,proto3" json:"float_ops,omitempty"`
	Trace                *CodeDef                        `protobuf:"bytes,10,opt,name=trace,proto3" json:"trace,omitempty"`
	Attrs                map[string]*framework.AttrValue `protobuf:"bytes,11,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Execs                map[int64]*ExecProfile          `protobuf:"bytes,12,rep,name=execs,proto3" json:"execs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProfileNode) Reset()         { *m = ProfileNode{} }
func (m *ProfileNode) String() string { return proto.CompactTextString(m) }
func (*ProfileNode) ProtoMessage()    {}
func (*ProfileNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{4}
}

func (m *ProfileNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileNode.Unmarshal(m, b)
}
func (m *ProfileNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileNode.Marshal(b, m, deterministic)
}
func (m *ProfileNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileNode.Merge(m, src)
}
func (m *ProfileNode) XXX_Size() int {
	return xxx_messageInfo_ProfileNode.Size(m)
}
func (m *ProfileNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileNode proto.InternalMessageInfo

func (m *ProfileNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileNode) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *ProfileNode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfileNode) GetInputs() map[int32]int64 {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *ProfileNode) GetInputShapes() map[int32]*Tuple {
	if m != nil {
		return m.InputShapes
	}
	return nil
}

func (m *ProfileNode) GetOutputs() map[int32]int64 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *ProfileNode) GetOutputShapes() map[int32]*Tuple {
	if m != nil {
		return m.OutputShapes
	}
	return nil
}

func (m *ProfileNode) GetSrcOutputIndex() map[int64]int32 {
	if m != nil {
		return m.SrcOutputIndex
	}
	return nil
}

func (m *ProfileNode) GetShape() []int64 {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *ProfileNode) GetOpTypes() []string {
	if m != nil {
		return m.OpTypes
	}
	return nil
}

func (m *ProfileNode) GetCanonicalDevice() string {
	if m != nil {
		return m.CanonicalDevice
	}
	return ""
}

func (m *ProfileNode) GetHostDevice() string {
	if m != nil {
		return m.HostDevice
	}
	return ""
}

func (m *ProfileNode) GetFloatOps() int64 {
	if m != nil {
		return m.FloatOps
	}
	return 0
}

func (m *ProfileNode) GetTrace() *CodeDef {
	if m != nil {
		return m.Trace
	}
	return nil
}

func (m *ProfileNode) GetAttrs() map[string]*framework.AttrValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *ProfileNode) GetExecs() map[int64]*ExecProfile {
	if m != nil {
		return m.Execs
	}
	return nil
}

type ExecProfile struct {
	// Can be larger than 1 if run multiple times in loop.
	RunCount int64 `protobuf:"varint,1,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	// The earliest/latest time including scheduling and execution.
	AllStartMicros  int64 `protobuf:"varint,2,opt,name=all_start_micros,json=allStartMicros,proto3" json:"all_start_micros,omitempty"`
	LatestEndMicros int64 `protobuf:"varint,3,opt,name=latest_end_micros,json=latestEndMicros,proto3" json:"latest_end_micros,omitempty"`
	// device -> vector of {op_start_micros, op_exec_micros} pairs.
	// accelerator_execs: gpu:id/stream:all -> {op_start_micros, op_exec_micros}
	// For accelerator, vector size can be larger than 1, multiple kernel fires
	// or in tf.while_loop.
	AcceleratorExecs map[string]*ExecTime `protobuf:"bytes,4,rep,name=accelerator_execs,json=acceleratorExecs,proto3" json:"accelerator_execs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// cpu_execs: cpu/gpu:id -> {op_start_micros, op_exec_micros}
	// For cpu, vector size can be larger than 1 if in tf.while_loop.
	CpuExecs map[string]*ExecTime `protobuf:"bytes,5,rep,name=cpu_execs,json=cpuExecs,proto3" json:"cpu_execs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Each entry to memory information of a scheduling of the node.
	// Normally, there will be multiple entries in while_loop.
	MemoryExecs []*ExecMemory `protobuf:"bytes,7,rep,name=memory_execs,json=memoryExecs,proto3" json:"memory_execs,omitempty"`
	// The allocation and deallocation times and sizes throughout execution.
	Allocations []*framework.AllocationRecord `protobuf:"bytes,11,rep,name=allocations,proto3" json:"allocations,omitempty"`
	// The devices related to this execution.
	Devices              []string `protobuf:"bytes,6,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecProfile) Reset()         { *m = ExecProfile{} }
func (m *ExecProfile) String() string { return proto.CompactTextString(m) }
func (*ExecProfile) ProtoMessage()    {}
func (*ExecProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{5}
}

func (m *ExecProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecProfile.Unmarshal(m, b)
}
func (m *ExecProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecProfile.Marshal(b, m, deterministic)
}
func (m *ExecProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecProfile.Merge(m, src)
}
func (m *ExecProfile) XXX_Size() int {
	return xxx_messageInfo_ExecProfile.Size(m)
}
func (m *ExecProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ExecProfile proto.InternalMessageInfo

func (m *ExecProfile) GetRunCount() int64 {
	if m != nil {
		return m.RunCount
	}
	return 0
}

func (m *ExecProfile) GetAllStartMicros() int64 {
	if m != nil {
		return m.AllStartMicros
	}
	return 0
}

func (m *ExecProfile) GetLatestEndMicros() int64 {
	if m != nil {
		return m.LatestEndMicros
	}
	return 0
}

func (m *ExecProfile) GetAcceleratorExecs() map[string]*ExecTime {
	if m != nil {
		return m.AcceleratorExecs
	}
	return nil
}

func (m *ExecProfile) GetCpuExecs() map[string]*ExecTime {
	if m != nil {
		return m.CpuExecs
	}
	return nil
}

func (m *ExecProfile) GetMemoryExecs() []*ExecMemory {
	if m != nil {
		return m.MemoryExecs
	}
	return nil
}

func (m *ExecProfile) GetAllocations() []*framework.AllocationRecord {
	if m != nil {
		return m.Allocations
	}
	return nil
}

func (m *ExecProfile) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

type ExecTime struct {
	Times                []*Tuple `protobuf:"bytes,1,rep,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecTime) Reset()         { *m = ExecTime{} }
func (m *ExecTime) String() string { return proto.CompactTextString(m) }
func (*ExecTime) ProtoMessage()    {}
func (*ExecTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{6}
}

func (m *ExecTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecTime.Unmarshal(m, b)
}
func (m *ExecTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecTime.Marshal(b, m, deterministic)
}
func (m *ExecTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecTime.Merge(m, src)
}
func (m *ExecTime) XXX_Size() int {
	return xxx_messageInfo_ExecTime.Size(m)
}
func (m *ExecTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecTime.DiscardUnknown(m)
}

var xxx_messageInfo_ExecTime proto.InternalMessageInfo

func (m *ExecTime) GetTimes() []*Tuple {
	if m != nil {
		return m.Times
	}
	return nil
}

type ExecMemory struct {
	// This is the timestamp when the memory information was tracked.
	MemoryMicros int64 `protobuf:"varint,1,opt,name=memory_micros,json=memoryMicros,proto3" json:"memory_micros,omitempty"`
	// NOTE: Please don't depend on the following 4 fields yet. Due to
	// TensorFlow internal tracing issues, the numbers can be quite wrong.
	// TODO(xpan): Fix the TensorFlow internal tracing.
	HostTempBytes              int64 `protobuf:"varint,2,opt,name=host_temp_bytes,json=hostTempBytes,proto3" json:"host_temp_bytes,omitempty"`
	HostPersistentBytes        int64 `protobuf:"varint,3,opt,name=host_persistent_bytes,json=hostPersistentBytes,proto3" json:"host_persistent_bytes,omitempty"`
	AcceleratorTempBytes       int64 `protobuf:"varint,4,opt,name=accelerator_temp_bytes,json=acceleratorTempBytes,proto3" json:"accelerator_temp_bytes,omitempty"`
	AcceleratorPersistentBytes int64 `protobuf:"varint,5,opt,name=accelerator_persistent_bytes,json=acceleratorPersistentBytes,proto3" json:"accelerator_persistent_bytes,omitempty"`
	// Total bytes requested by the op.
	RequestedBytes int64 `protobuf:"varint,6,opt,name=requested_bytes,json=requestedBytes,proto3" json:"requested_bytes,omitempty"`
	// Total bytes requested by the op and released before op end.
	PeakBytes int64 `protobuf:"varint,7,opt,name=peak_bytes,json=peakBytes,proto3" json:"peak_bytes,omitempty"`
	// Total bytes requested by the op and not released after op end.
	ResidualBytes int64 `protobuf:"varint,8,opt,name=residual_bytes,json=residualBytes,proto3" json:"residual_bytes,omitempty"`
	// Total bytes output by the op (not necessarily requested by the op).
	OutputBytes int64 `protobuf:"varint,9,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	// The total number of bytes currently allocated by the allocator if >0.
	AllocatorBytesInUse int64 `protobuf:"varint,10,opt,name=allocator_bytes_in_use,json=allocatorBytesInUse,proto3" json:"allocator_bytes_in_use,omitempty"`
	// The memory of each output of the operation.
	OutputMemory         map[int32]*Memory `protobuf:"bytes,11,rep,name=output_memory,json=outputMemory,proto3" json:"output_memory,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExecMemory) Reset()         { *m = ExecMemory{} }
func (m *ExecMemory) String() string { return proto.CompactTextString(m) }
func (*ExecMemory) ProtoMessage()    {}
func (*ExecMemory) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{7}
}

func (m *ExecMemory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecMemory.Unmarshal(m, b)
}
func (m *ExecMemory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecMemory.Marshal(b, m, deterministic)
}
func (m *ExecMemory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecMemory.Merge(m, src)
}
func (m *ExecMemory) XXX_Size() int {
	return xxx_messageInfo_ExecMemory.Size(m)
}
func (m *ExecMemory) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecMemory.DiscardUnknown(m)
}

var xxx_messageInfo_ExecMemory proto.InternalMessageInfo

func (m *ExecMemory) GetMemoryMicros() int64 {
	if m != nil {
		return m.MemoryMicros
	}
	return 0
}

func (m *ExecMemory) GetHostTempBytes() int64 {
	if m != nil {
		return m.HostTempBytes
	}
	return 0
}

func (m *ExecMemory) GetHostPersistentBytes() int64 {
	if m != nil {
		return m.HostPersistentBytes
	}
	return 0
}

func (m *ExecMemory) GetAcceleratorTempBytes() int64 {
	if m != nil {
		return m.AcceleratorTempBytes
	}
	return 0
}

func (m *ExecMemory) GetAcceleratorPersistentBytes() int64 {
	if m != nil {
		return m.AcceleratorPersistentBytes
	}
	return 0
}

func (m *ExecMemory) GetRequestedBytes() int64 {
	if m != nil {
		return m.RequestedBytes
	}
	return 0
}

func (m *ExecMemory) GetPeakBytes() int64 {
	if m != nil {
		return m.PeakBytes
	}
	return 0
}

func (m *ExecMemory) GetResidualBytes() int64 {
	if m != nil {
		return m.ResidualBytes
	}
	return 0
}

func (m *ExecMemory) GetOutputBytes() int64 {
	if m != nil {
		return m.OutputBytes
	}
	return 0
}

func (m *ExecMemory) GetAllocatorBytesInUse() int64 {
	if m != nil {
		return m.AllocatorBytesInUse
	}
	return 0
}

func (m *ExecMemory) GetOutputMemory() map[int32]*Memory {
	if m != nil {
		return m.OutputMemory
	}
	return nil
}

type Tuple struct {
	Int64Values          []int64  `protobuf:"varint,1,rep,packed,name=int64_values,json=int64Values,proto3" json:"int64_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{8}
}

func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetInt64Values() []int64 {
	if m != nil {
		return m.Int64Values
	}
	return nil
}

type Memory struct {
	Bytes                int64    `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Ptr                  uint64   `protobuf:"varint,2,opt,name=ptr,proto3" json:"ptr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memory) Reset()         { *m = Memory{} }
func (m *Memory) String() string { return proto.CompactTextString(m) }
func (*Memory) ProtoMessage()    {}
func (*Memory) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cf3615e51b11da, []int{9}
}

func (m *Memory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memory.Unmarshal(m, b)
}
func (m *Memory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memory.Marshal(b, m, deterministic)
}
func (m *Memory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memory.Merge(m, src)
}
func (m *Memory) XXX_Size() int {
	return xxx_messageInfo_Memory.Size(m)
}
func (m *Memory) XXX_DiscardUnknown() {
	xxx_messageInfo_Memory.DiscardUnknown(m)
}

var xxx_messageInfo_Memory proto.InternalMessageInfo

func (m *Memory) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *Memory) GetPtr() uint64 {
	if m != nil {
		return m.Ptr
	}
	return 0
}

func init() {
	proto.RegisterType((*CodeDef)(nil), "tensorflow.tfprof.CodeDef")
	proto.RegisterType((*CodeDef_Trace)(nil), "tensorflow.tfprof.CodeDef.Trace")
	proto.RegisterType((*OpLogEntry)(nil), "tensorflow.tfprof.OpLogEntry")
	proto.RegisterType((*OpLogProto)(nil), "tensorflow.tfprof.OpLogProto")
	proto.RegisterMapType((map[int64]string)(nil), "tensorflow.tfprof.OpLogProto.IdToStringEntry")
	proto.RegisterType((*ProfileProto)(nil), "tensorflow.tfprof.ProfileProto")
	proto.RegisterMapType((map[int64]string)(nil), "tensorflow.tfprof.ProfileProto.IdToStringEntry")
	proto.RegisterMapType((map[int64]*ProfileNode)(nil), "tensorflow.tfprof.ProfileProto.NodesEntry")
	proto.RegisterType((*ProfileNode)(nil), "tensorflow.tfprof.ProfileNode")
	proto.RegisterMapType((map[string]*framework.AttrValue)(nil), "tensorflow.tfprof.ProfileNode.AttrsEntry")
	proto.RegisterMapType((map[int64]*ExecProfile)(nil), "tensorflow.tfprof.ProfileNode.ExecsEntry")
	proto.RegisterMapType((map[int32]*Tuple)(nil), "tensorflow.tfprof.ProfileNode.InputShapesEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "tensorflow.tfprof.ProfileNode.InputsEntry")
	proto.RegisterMapType((map[int32]*Tuple)(nil), "tensorflow.tfprof.ProfileNode.OutputShapesEntry")
	proto.RegisterMapType((map[int32]int64)(nil), "tensorflow.tfprof.ProfileNode.OutputsEntry")
	proto.RegisterMapType((map[int64]int32)(nil), "tensorflow.tfprof.ProfileNode.SrcOutputIndexEntry")
	proto.RegisterType((*ExecProfile)(nil), "tensorflow.tfprof.ExecProfile")
	proto.RegisterMapType((map[string]*ExecTime)(nil), "tensorflow.tfprof.ExecProfile.AcceleratorExecsEntry")
	proto.RegisterMapType((map[string]*ExecTime)(nil), "tensorflow.tfprof.ExecProfile.CpuExecsEntry")
	proto.RegisterType((*ExecTime)(nil), "tensorflow.tfprof.ExecTime")
	proto.RegisterType((*ExecMemory)(nil), "tensorflow.tfprof.ExecMemory")
	proto.RegisterMapType((map[int32]*Memory)(nil), "tensorflow.tfprof.ExecMemory.OutputMemoryEntry")
	proto.RegisterType((*Tuple)(nil), "tensorflow.tfprof.Tuple")
	proto.RegisterType((*Memory)(nil), "tensorflow.tfprof.Memory")
}

func init() {
	proto.RegisterFile("tensorflow/core/profiler/tfprof_log.proto", fileDescriptor_82cf3615e51b11da)
}

var fileDescriptor_82cf3615e51b11da = []byte{
	// 1456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x72, 0xdb, 0x36,
	0x13, 0x1e, 0x89, 0xa2, 0x0e, 0x2b, 0x1f, 0x91, 0xd8, 0x61, 0x94, 0xc3, 0xef, 0xdf, 0x9d, 0xa6,
	0x8e, 0xd3, 0x4a, 0xa9, 0xe3, 0x66, 0xd2, 0xcc, 0x34, 0x8d, 0xed, 0xf8, 0xc2, 0x33, 0x49, 0x9d,
	0xd2, 0x4a, 0x27, 0xcd, 0x74, 0x86, 0x65, 0x48, 0xc8, 0xe6, 0x84, 0x22, 0x58, 0x02, 0x4c, 0xe2,
	0x17, 0xe8, 0x45, 0x5f, 0xa4, 0xb7, 0x7d, 0x81, 0xbe, 0x49, 0x9f, 0xa0, 0x0f, 0xd1, 0xe9, 0x60,
	0x17, 0x92, 0x28, 0x45, 0xb6, 0xd2, 0x36, 0x57, 0x04, 0x16, 0xdf, 0x7e, 0x58, 0x2c, 0x3e, 0x2c,
	0x40, 0xb8, 0xa9, 0x78, 0x22, 0x45, 0xd6, 0x8b, 0xc5, 0x9b, 0x4e, 0x20, 0x32, 0xde, 0x49, 0x33,
	0xd1, 0x8b, 0x62, 0x9e, 0x75, 0x54, 0x4f, 0x37, 0xbd, 0x58, 0x1c, 0xb7, 0xd3, 0x4c, 0x28, 0xc1,
	0x96, 0x47, 0xd0, 0x36, 0x0d, 0xb6, 0x36, 0x27, 0xbd, 0x7b, 0x99, 0xdf, 0xe7, 0x6f, 0x44, 0xf6,
	0xaa, 0xe3, 0x2b, 0x95, 0x79, 0xaf, 0xfd, 0x38, 0xe7, 0xe4, 0x7e, 0x1e, 0x56, 0x2a, 0x9e, 0x7a,
	0x52, 0xf9, 0x4a, 0x12, 0x76, 0xfd, 0xb7, 0x32, 0xd4, 0xf6, 0x44, 0xc8, 0x1f, 0xf1, 0x1e, 0xbb,
	0x07, 0x55, 0x95, 0xf9, 0x01, 0x97, 0x4e, 0x69, 0xcd, 0xda, 0x68, 0x6e, 0xad, 0xb5, 0xdf, 0x89,
	0xa3, 0x6d, 0xb0, 0xed, 0xae, 0x06, 0xba, 0x06, 0xdf, 0xfa, 0xb3, 0x04, 0x36, 0x5a, 0xd8, 0x2a,
	0x54, 0xf4, 0xa2, 0x9c, 0xd2, 0x5a, 0x69, 0xa3, 0xb1, 0x5b, 0x76, 0x4a, 0x2e, 0xf6, 0xd9, 0x25,
	0xa8, 0xe9, 0xaf, 0x17, 0x85, 0x4e, 0x75, 0xad, 0xb4, 0x61, 0xb9, 0x55, 0xdd, 0x3d, 0x08, 0xd9,
	0x2a, 0x54, 0xe3, 0x28, 0xe1, 0x89, 0x70, 0xca, 0x6b, 0xa5, 0x0d, 0xdb, 0x35, 0x3d, 0x76, 0x1d,
	0xea, 0xbd, 0x3c, 0x09, 0x54, 0x24, 0x12, 0xc7, 0x1a, 0x92, 0x0d, 0x6d, 0xec, 0x7f, 0xd0, 0x1c,
	0xb4, 0x35, 0x69, 0x0d, 0x49, 0x61, 0x60, 0x42, 0xe2, 0x8a, 0xa6, 0x72, 0x2a, 0xa3, 0x48, 0x74,
	0x5f, 0x47, 0xa2, 0xbf, 0xda, 0xa9, 0x4e, 0x91, 0xe8, 0xee, 0x41, 0xc8, 0x6e, 0xc0, 0xa2, 0x76,
	0xd7, 0xe9, 0xc9, 0x94, 0x87, 0xbe, 0x36, 0x86, 0x34, 0xaf, 0xcd, 0x47, 0xda, 0xfa, 0x38, 0x4a,
	0xf8, 0xfa, 0x2f, 0x25, 0x80, 0xc3, 0xf4, 0xb1, 0x38, 0xde, 0x4f, 0x54, 0x76, 0xca, 0x18, 0x54,
	0x12, 0xbf, 0x6f, 0x56, 0xec, 0x62, 0x9b, 0x5d, 0x81, 0x46, 0x2f, 0x16, 0xbe, 0xf2, 0x44, 0x2a,
	0x71, 0x5d, 0x96, 0x5b, 0x47, 0xc3, 0x61, 0x2a, 0xd9, 0x45, 0xb0, 0xd5, 0x69, 0xca, 0xa5, 0x63,
	0xad, 0x59, 0x1b, 0x0d, 0x97, 0x3a, 0xec, 0x0b, 0xa8, 0x07, 0x22, 0xe4, 0x5e, 0xc8, 0x7b, 0x18,
	0x72, 0x73, 0xab, 0x75, 0x76, 0xfa, 0xdd, 0x5a, 0x40, 0x8d, 0xf5, 0x3f, 0x06, 0xc1, 0x3c, 0x45,
	0xe5, 0x3c, 0x80, 0x66, 0x2c, 0x8e, 0x3d, 0x9e, 0xa8, 0x2c, 0x1a, 0xee, 0xe3, 0xb5, 0x29, 0x44,
	0xa3, 0x05, 0xb8, 0x10, 0x53, 0x2b, 0xe2, 0x92, 0x1d, 0xc2, 0x5c, 0x14, 0x7a, 0x4a, 0x78, 0x52,
	0x65, 0x51, 0x72, 0xec, 0x94, 0x91, 0xe0, 0xb3, 0xb3, 0x08, 0x70, 0xd2, 0xf6, 0x41, 0xd8, 0x15,
	0x47, 0x88, 0x37, 0x84, 0xd1, 0xd0, 0xd0, 0xfa, 0x0a, 0x16, 0x27, 0x86, 0xd9, 0x12, 0x58, 0xaf,
	0xf8, 0x29, 0xe6, 0xcb, 0x72, 0x75, 0x53, 0x67, 0x04, 0xf5, 0x8b, 0xa9, 0x6a, 0xb8, 0xd4, 0xb9,
	0x5f, 0xbe, 0x57, 0x5a, 0xff, 0xd5, 0x82, 0xb9, 0xa7, 0x74, 0x4e, 0x68, 0x81, 0x0f, 0xc1, 0x4e,
	0x44, 0x38, 0x5c, 0xda, 0xe6, 0x94, 0xc8, 0x8a, 0xf8, 0xf6, 0x37, 0x1a, 0x4c, 0x61, 0x91, 0xa3,
	0xde, 0x9b, 0x13, 0x5f, 0x7a, 0xa8, 0x5c, 0x9c, 0xb0, 0xee, 0xd6, 0x4f, 0x7c, 0x49, 0xf2, 0xbd,
	0x0b, 0x97, 0xfa, 0x91, 0x94, 0x9e, 0x1f, 0x04, 0x3c, 0xe6, 0x99, 0xaf, 0x44, 0xa6, 0x53, 0xc1,
	0xfd, 0x3e, 0x6a, 0xa1, 0xee, 0xae, 0xe8, 0xe1, 0x9d, 0xd1, 0xe8, 0x11, 0x0e, 0xea, 0x15, 0xe8,
	0xa3, 0x45, 0x7b, 0x6a, 0xb9, 0xd4, 0x61, 0xdf, 0x4e, 0x64, 0xb3, 0x82, 0x31, 0x77, 0x66, 0xc5,
	0x7c, 0x5e, 0x3e, 0x9f, 0x03, 0x8c, 0x96, 0x34, 0x25, 0x95, 0xdb, 0xc5, 0x54, 0x36, 0xb7, 0xae,
	0x9f, 0x3d, 0x97, 0xa6, 0x29, 0xa4, 0xfa, 0xbf, 0xee, 0xd4, 0xef, 0x00, 0xcd, 0x02, 0xf3, 0xd4,
	0x63, 0xb1, 0x00, 0x65, 0x91, 0x3a, 0x0d, 0xb4, 0x94, 0x45, 0xaa, 0xfb, 0x51, 0xe8, 0xcc, 0x23,
	0x7d, 0x39, 0x0a, 0xd9, 0x2e, 0x54, 0xa3, 0x24, 0xcd, 0x95, 0x34, 0xba, 0xdb, 0x3c, 0x3f, 0xfa,
	0xf6, 0x01, 0x82, 0x29, 0x49, 0xc6, 0x93, 0xb9, 0x30, 0x87, 0x2d, 0x4f, 0x9e, 0xf8, 0xfa, 0x90,
	0x2d, 0xcd, 0xca, 0xf9, 0x88, 0xe9, 0x08, 0x3d, 0x88, 0xae, 0x19, 0x8d, 0x2c, 0x6c, 0x1f, 0x6a,
	0x22, 0x57, 0x18, 0x98, 0x85, 0x74, 0xb7, 0x66, 0xd0, 0x1d, 0x12, 0x9a, 0xa8, 0x06, 0xbe, 0xec,
	0x19, 0xcc, 0x53, 0x73, 0x10, 0xdb, 0x22, 0x92, 0xdd, 0x7e, 0x2f, 0xb2, 0x62, 0x70, 0x73, 0xa2,
	0x60, 0x62, 0x3f, 0xc0, 0x92, 0xcc, 0x02, 0xcf, 0x50, 0x47, 0x49, 0xc8, 0xdf, 0x3a, 0x0b, 0xc8,
	0xbc, 0x35, 0x83, 0xf9, 0x28, 0x0b, 0x88, 0xfc, 0x40, 0x3b, 0x11, 0xf7, 0x82, 0x1c, 0x33, 0xa2,
	0xb2, 0xf5, 0x3c, 0x28, 0x5e, 0xad, 0x6c, 0xdd, 0x61, 0x97, 0xa1, 0x2e, 0x52, 0x8f, 0xca, 0x98,
	0x8d, 0x65, 0xac, 0x26, 0xd2, 0x2e, 0x16, 0xb2, 0x9b, 0xb0, 0x14, 0xf8, 0x89, 0x48, 0xa2, 0xc0,
	0x8f, 0xbd, 0x90, 0xbf, 0x8e, 0x02, 0x8e, 0x25, 0xbf, 0xe1, 0x2e, 0x0e, 0xed, 0x8f, 0xd0, 0xac,
	0x6b, 0xf8, 0x89, 0x90, 0x6a, 0x80, 0xaa, 0x21, 0x0a, 0xb4, 0xc9, 0x00, 0xc6, 0xea, 0x68, 0x7d,
	0xa2, 0x8e, 0xde, 0x06, 0x9b, 0x0e, 0x31, 0xcc, 0x2c, 0x97, 0x04, 0x64, 0x5f, 0x83, 0xad, 0x2f,
	0x4b, 0xe9, 0x34, 0x31, 0x3d, 0x37, 0x67, 0xa4, 0x67, 0x47, 0x63, 0x4d, 0xed, 0x40, 0x3f, 0x4d,
	0xc0, 0xdf, 0xf2, 0x40, 0x3a, 0x73, 0xef, 0x45, 0xb0, 0xaf, 0xb1, 0x86, 0x00, 0xfd, 0x5a, 0x5f,
	0x42, 0xb3, 0x20, 0xda, 0xe2, 0x01, 0xb3, 0xa7, 0x1c, 0x30, 0xab, 0x78, 0x3e, 0x9f, 0xc3, 0xd2,
	0xa4, 0x4a, 0xa7, 0xf8, 0xb7, 0xc7, 0xcf, 0xbf, 0x33, 0x25, 0xc2, 0x6e, 0x9e, 0xc6, 0x63, 0x27,
	0xff, 0x3e, 0xcc, 0x15, 0x05, 0xfb, 0x8f, 0xa2, 0xfa, 0x1e, 0x96, 0xdf, 0xd1, 0xe7, 0x07, 0x0a,
	0x6b, 0x07, 0x2e, 0x4c, 0x11, 0xe8, 0xac, 0xa2, 0x64, 0x17, 0x29, 0x0e, 0x01, 0x46, 0x9b, 0x58,
	0xf4, 0x6c, 0x90, 0xe7, 0xad, 0xf1, 0xb0, 0x56, 0x8a, 0x61, 0x69, 0xc7, 0xef, 0xf4, 0xe0, 0xf8,
	0x26, 0xc0, 0x68, 0x53, 0xff, 0x5d, 0xf9, 0xd5, 0xfe, 0x46, 0x24, 0xc5, 0xfa, 0xf9, 0xb3, 0x0d,
	0xcd, 0xc2, 0x90, 0x96, 0x7e, 0x96, 0x27, 0x5e, 0x20, 0xf2, 0x44, 0x99, 0x19, 0xea, 0x59, 0x9e,
	0xec, 0xe9, 0x3e, 0xdb, 0x80, 0x25, 0x3f, 0x8e, 0xcd, 0x4b, 0xa5, 0x1f, 0x05, 0x99, 0x18, 0x3c,
	0x33, 0x16, 0xfc, 0x38, 0xc6, 0xa7, 0xca, 0x13, 0xb4, 0xb2, 0x4d, 0x58, 0x8e, 0x7d, 0xc5, 0xa5,
	0xf2, 0x78, 0x12, 0x0e, 0xa0, 0x16, 0x42, 0x17, 0x69, 0x60, 0x3f, 0x09, 0x0d, 0xd6, 0x87, 0xe5,
	0xe2, 0xbd, 0x47, 0x4a, 0xa7, 0x3b, 0x6b, 0xfb, 0xfc, 0x85, 0xb4, 0x0b, 0x37, 0x62, 0x41, 0xf4,
	0x4b, 0xfe, 0x84, 0x99, 0x1d, 0x40, 0x23, 0x48, 0x73, 0x43, 0x6d, 0x23, 0xf5, 0xa7, 0x33, 0xa8,
	0xf7, 0xd2, 0xbc, 0x40, 0x59, 0x0f, 0x4c, 0x97, 0x3d, 0x84, 0xb9, 0x3e, 0xef, 0x8b, 0xec, 0xd4,
	0xb0, 0xd5, 0xce, 0x7c, 0xeb, 0x68, 0xfc, 0x13, 0x84, 0xba, 0x4d, 0x72, 0x21, 0x86, 0x07, 0xd0,
	0xf4, 0xe3, 0x58, 0x04, 0xbe, 0x7e, 0x31, 0x0e, 0x8a, 0xc2, 0xd5, 0x31, 0x0d, 0x0c, 0x87, 0x5d,
	0x1e, 0x88, 0x2c, 0x74, 0x8b, 0x0e, 0xcc, 0x81, 0x1a, 0x55, 0x2e, 0xe9, 0x54, 0xa9, 0x06, 0x9a,
	0x6e, 0xeb, 0x47, 0x58, 0x99, 0x9a, 0x91, 0x29, 0x12, 0xfc, 0x7c, 0x5c, 0x31, 0x57, 0xce, 0x88,
	0xbf, 0x1b, 0xf5, 0x27, 0x84, 0x38, 0x3f, 0x96, 0x98, 0x0f, 0xc6, 0xbc, 0x7e, 0x1f, 0xea, 0x03,
	0xb3, 0x3e, 0xb6, 0x2a, 0xea, 0x0f, 0x5f, 0x5b, 0xe7, 0x1c, 0x5b, 0x84, 0xad, 0xff, 0x55, 0xa1,
	0xf3, 0x41, 0xd9, 0x66, 0x1f, 0xc1, 0xbc, 0xd9, 0x22, 0x23, 0x3c, 0xd2, 0xb1, 0xd9, 0x37, 0xa3,
	0xba, 0x1b, 0xb0, 0x88, 0x97, 0x80, 0xe2, 0xfd, 0xd4, 0x7b, 0x79, 0xaa, 0xf8, 0x40, 0xca, 0xf3,
	0xda, 0xdc, 0xe5, 0xfd, 0x74, 0x57, 0x1b, 0xd9, 0x16, 0xac, 0x20, 0x2e, 0xe5, 0x99, 0x8c, 0xa4,
	0xe2, 0x89, 0x32, 0x68, 0x52, 0xf3, 0x05, 0x3d, 0xf8, 0x74, 0x38, 0x46, 0x3e, 0xdb, 0xb0, 0x5a,
	0x54, 0x74, 0x61, 0x8a, 0x0a, 0x3a, 0x5d, 0x2c, 0x8c, 0x8e, 0x66, 0x7a, 0x08, 0x57, 0x8b, 0x5e,
	0xef, 0x4c, 0x68, 0xa3, 0x6f, 0xab, 0x80, 0x99, 0x9c, 0xf7, 0x13, 0x58, 0xcc, 0xf8, 0x4f, 0x39,
	0x97, 0x8a, 0x87, 0xc6, 0x89, 0xfe, 0x7a, 0x16, 0x86, 0x66, 0x02, 0x5e, 0x03, 0x48, 0xb9, 0xff,
	0xca, 0x60, 0xe8, 0x27, 0xa6, 0xa1, 0x2d, 0x34, 0xfc, 0x31, 0x2c, 0x64, 0x5c, 0x46, 0x61, 0xee,
	0xc7, 0x06, 0x42, 0x97, 0xe0, 0xfc, 0xc0, 0x4a, 0xb0, 0xff, 0x83, 0x79, 0x11, 0x18, 0x50, 0x03,
	0x41, 0x4d, 0xb2, 0x11, 0xe4, 0x0e, 0xac, 0x1a, 0xe9, 0x8a, 0x8c, 0x50, 0x5e, 0x94, 0x78, 0xb9,
	0xa4, 0xdb, 0xd3, 0x72, 0x2f, 0x0c, 0x47, 0x11, 0x7f, 0x90, 0x3c, 0x93, 0x9c, 0x75, 0x87, 0x0f,
	0x16, 0xda, 0x31, 0x73, 0x44, 0x3a, 0xe7, 0x9e, 0x31, 0xf3, 0x5e, 0xa1, 0xce, 0xd8, 0x7b, 0x85,
	0x4c, 0xad, 0x17, 0x83, 0x2b, 0xa3, 0x00, 0x99, 0x72, 0x65, 0x74, 0xc6, 0xe5, 0x7b, 0x79, 0xca,
	0xa4, 0xe6, 0x50, 0x17, 0xc4, 0xbb, 0x09, 0x36, 0x0a, 0x52, 0xa7, 0x24, 0x4a, 0xd4, 0xdd, 0x6d,
	0xfa, 0x31, 0x26, 0x01, 0x5b, 0xfa, 0x55, 0xa7, 0xee, 0x6e, 0x63, 0x55, 0x97, 0xeb, 0xb7, 0xa1,
	0x6a, 0x74, 0x7a, 0x11, 0x6c, 0x4a, 0x1c, 0xe9, 0x93, 0x3a, 0x3a, 0xa4, 0x54, 0x65, 0x38, 0x7d,
	0xc5, 0xd5, 0xcd, 0xdd, 0xbd, 0x17, 0x3b, 0xc7, 0x91, 0x3a, 0xc9, 0x5f, 0xb6, 0x03, 0xd1, 0xef,
	0x14, 0xfe, 0xb2, 0xa7, 0x37, 0x8f, 0x05, 0xfd, 0x7e, 0x8f, 0xfd, 0xed, 0xbf, 0xac, 0xe2, 0x8f,
	0xf7, 0x9d, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xe0, 0x9f, 0x3c, 0x10, 0x10, 0x00, 0x00,
}
