// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/contrib/boosted_trees/proto/quantiles.proto

package boosted_trees

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuantileConfig struct {
	// Maximum eps error when computing quantile summaries.
	Eps float64 `protobuf:"fixed64,1,opt,name=eps,proto3" json:"eps,omitempty"`
	// Number of quantiles to generate.
	NumQuantiles         int64    `protobuf:"varint,2,opt,name=num_quantiles,json=numQuantiles,proto3" json:"num_quantiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuantileConfig) Reset()         { *m = QuantileConfig{} }
func (m *QuantileConfig) String() string { return proto.CompactTextString(m) }
func (*QuantileConfig) ProtoMessage()    {}
func (*QuantileConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3501c968900bb37e, []int{0}
}

func (m *QuantileConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuantileConfig.Unmarshal(m, b)
}
func (m *QuantileConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuantileConfig.Marshal(b, m, deterministic)
}
func (m *QuantileConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuantileConfig.Merge(m, src)
}
func (m *QuantileConfig) XXX_Size() int {
	return xxx_messageInfo_QuantileConfig.Size(m)
}
func (m *QuantileConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_QuantileConfig.DiscardUnknown(m)
}

var xxx_messageInfo_QuantileConfig proto.InternalMessageInfo

func (m *QuantileConfig) GetEps() float64 {
	if m != nil {
		return m.Eps
	}
	return 0
}

func (m *QuantileConfig) GetNumQuantiles() int64 {
	if m != nil {
		return m.NumQuantiles
	}
	return 0
}

type QuantileEntry struct {
	// Value for the entry.
	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	// Weight for the entry.
	Weight float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// We need the minimum and maximum rank possible for this entry.
	// Rank is 0.0 for the absolute minimum and sum of the weights for the maximum
	// value in the input.
	MinRank              float32  `protobuf:"fixed32,3,opt,name=min_rank,json=minRank,proto3" json:"min_rank,omitempty"`
	MaxRank              float32  `protobuf:"fixed32,4,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuantileEntry) Reset()         { *m = QuantileEntry{} }
func (m *QuantileEntry) String() string { return proto.CompactTextString(m) }
func (*QuantileEntry) ProtoMessage()    {}
func (*QuantileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3501c968900bb37e, []int{1}
}

func (m *QuantileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuantileEntry.Unmarshal(m, b)
}
func (m *QuantileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuantileEntry.Marshal(b, m, deterministic)
}
func (m *QuantileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuantileEntry.Merge(m, src)
}
func (m *QuantileEntry) XXX_Size() int {
	return xxx_messageInfo_QuantileEntry.Size(m)
}
func (m *QuantileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_QuantileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_QuantileEntry proto.InternalMessageInfo

func (m *QuantileEntry) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *QuantileEntry) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *QuantileEntry) GetMinRank() float32 {
	if m != nil {
		return m.MinRank
	}
	return 0
}

func (m *QuantileEntry) GetMaxRank() float32 {
	if m != nil {
		return m.MaxRank
	}
	return 0
}

type QuantileSummaryState struct {
	Entries              []*QuantileEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QuantileSummaryState) Reset()         { *m = QuantileSummaryState{} }
func (m *QuantileSummaryState) String() string { return proto.CompactTextString(m) }
func (*QuantileSummaryState) ProtoMessage()    {}
func (*QuantileSummaryState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3501c968900bb37e, []int{2}
}

func (m *QuantileSummaryState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuantileSummaryState.Unmarshal(m, b)
}
func (m *QuantileSummaryState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuantileSummaryState.Marshal(b, m, deterministic)
}
func (m *QuantileSummaryState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuantileSummaryState.Merge(m, src)
}
func (m *QuantileSummaryState) XXX_Size() int {
	return xxx_messageInfo_QuantileSummaryState.Size(m)
}
func (m *QuantileSummaryState) XXX_DiscardUnknown() {
	xxx_messageInfo_QuantileSummaryState.DiscardUnknown(m)
}

var xxx_messageInfo_QuantileSummaryState proto.InternalMessageInfo

func (m *QuantileSummaryState) GetEntries() []*QuantileEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type QuantileStreamState struct {
	Summaries            []*QuantileSummaryState `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QuantileStreamState) Reset()         { *m = QuantileStreamState{} }
func (m *QuantileStreamState) String() string { return proto.CompactTextString(m) }
func (*QuantileStreamState) ProtoMessage()    {}
func (*QuantileStreamState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3501c968900bb37e, []int{3}
}

func (m *QuantileStreamState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuantileStreamState.Unmarshal(m, b)
}
func (m *QuantileStreamState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuantileStreamState.Marshal(b, m, deterministic)
}
func (m *QuantileStreamState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuantileStreamState.Merge(m, src)
}
func (m *QuantileStreamState) XXX_Size() int {
	return xxx_messageInfo_QuantileStreamState.Size(m)
}
func (m *QuantileStreamState) XXX_DiscardUnknown() {
	xxx_messageInfo_QuantileStreamState.DiscardUnknown(m)
}

var xxx_messageInfo_QuantileStreamState proto.InternalMessageInfo

func (m *QuantileStreamState) GetSummaries() []*QuantileSummaryState {
	if m != nil {
		return m.Summaries
	}
	return nil
}

func init() {
	proto.RegisterType((*QuantileConfig)(nil), "boosted_trees.QuantileConfig")
	proto.RegisterType((*QuantileEntry)(nil), "boosted_trees.QuantileEntry")
	proto.RegisterType((*QuantileSummaryState)(nil), "boosted_trees.QuantileSummaryState")
	proto.RegisterType((*QuantileStreamState)(nil), "boosted_trees.QuantileStreamState")
}

func init() {
	proto.RegisterFile("tensorflow/contrib/boosted_trees/proto/quantiles.proto", fileDescriptor_3501c968900bb37e)
}

var fileDescriptor_3501c968900bb37e = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4f, 0x32, 0x31,
	0x10, 0xc5, 0xb3, 0xec, 0xf7, 0x81, 0x8e, 0x62, 0x4c, 0x25, 0x06, 0x13, 0x0f, 0x64, 0xb9, 0x70,
	0xda, 0x4d, 0x34, 0xe1, 0xae, 0xc6, 0x18, 0x2f, 0x24, 0x96, 0x8b, 0xf1, 0x42, 0xba, 0x38, 0x2c,
	0x0d, 0xb4, 0xc5, 0x76, 0x56, 0xe0, 0x3f, 0xf7, 0x68, 0xb6, 0xb0, 0xc0, 0x26, 0x78, 0x9b, 0x97,
	0x37, 0xf3, 0xeb, 0x4c, 0x1f, 0xf4, 0x09, 0xb5, 0x33, 0x76, 0x32, 0x37, 0xcb, 0x64, 0x6c, 0x34,
	0x59, 0x99, 0x26, 0xa9, 0x31, 0x8e, 0xf0, 0x73, 0x44, 0x16, 0xd1, 0x25, 0x0b, 0x6b, 0xc8, 0x24,
	0x5f, 0xb9, 0xd0, 0x24, 0xe7, 0xe8, 0x62, 0xaf, 0x59, 0xb3, 0xd2, 0x14, 0xbd, 0xc0, 0xc5, 0xdb,
	0xb6, 0xe3, 0xc9, 0xe8, 0x89, 0xcc, 0xd8, 0x25, 0x84, 0xb8, 0x70, 0xed, 0xa0, 0x13, 0xf4, 0x02,
	0x5e, 0x94, 0xac, 0x0b, 0x4d, 0x9d, 0xab, 0xd1, 0x8e, 0xd4, 0xae, 0x75, 0x82, 0x5e, 0xc8, 0xcf,
	0x75, 0xae, 0xca, 0x59, 0x17, 0x39, 0x68, 0x96, 0xe2, 0x59, 0x93, 0x5d, 0xb3, 0x16, 0xfc, 0xff,
	0x16, 0xf3, 0x1c, 0x3d, 0xa9, 0xc6, 0x37, 0x82, 0x5d, 0x43, 0x7d, 0x89, 0x32, 0x9b, 0x92, 0x87,
	0xd4, 0xf8, 0x56, 0xb1, 0x1b, 0x38, 0x51, 0x52, 0x8f, 0xac, 0xd0, 0xb3, 0x76, 0xe8, 0x9d, 0x86,
	0x92, 0x9a, 0x0b, 0x3d, 0xf3, 0x96, 0x58, 0x6d, 0xac, 0x7f, 0x5b, 0x4b, 0xac, 0x0a, 0x2b, 0x1a,
	0x40, 0xab, 0x7c, 0x74, 0x98, 0x2b, 0x25, 0xec, 0x7a, 0x48, 0x82, 0x90, 0xf5, 0xa1, 0x81, 0xc5,
	0x97, 0x60, 0x71, 0x47, 0xd8, 0x3b, 0xbb, 0xbb, 0x8d, 0x2b, 0x67, 0xc7, 0x95, 0x55, 0x79, 0xd9,
	0x1c, 0xbd, 0xc3, 0xd5, 0x8e, 0x47, 0x16, 0x85, 0xda, 0xe0, 0x1e, 0xe0, 0xd4, 0x79, 0xfc, 0x1e,
	0xd8, 0xfd, 0x03, 0x78, 0xb8, 0x06, 0xdf, 0x4f, 0x3d, 0x0e, 0x3e, 0x5e, 0x33, 0x49, 0xd3, 0x3c,
	0x8d, 0xc7, 0x46, 0x25, 0x07, 0xd9, 0x1d, 0x2f, 0x33, 0x93, 0x8c, 0x8d, 0xc5, 0xe3, 0xc9, 0xfe,
	0x04, 0x41, 0x5a, 0xf7, 0x69, 0xde, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x10, 0x1c, 0x69, 0x07,
	0x07, 0x02, 0x00, 0x00,
}
